# Persian translation for apport
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-11-19 08:43+0100\n"
"PO-Revision-Date: 2011-10-07 06:10+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Persian <fa@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2014-05-22 05:29+0000\n"
"X-Generator: Launchpad (build 17017)\n"
"Language: fa\n"

#: ../apport/ui.py:124
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:124
msgid "This package does not seem to be installed correctly"
msgstr ""

#: ../apport/ui.py:128
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:128
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""

#: ../apport/ui.py:145
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:145
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""

#: ../apport/ui.py:269
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:269
msgid "unknown program"
msgstr ""

#: ../apport/ui.py:270
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:270
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr ""

#: ../apport/ui.py:272 ../apport/ui.py:1298
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:272
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1298
#, python-format
msgid "Problem in %s"
msgstr ""

#: ../apport/ui.py:273
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:273
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""

#: ../apport/ui.py:321 ../apport/ui.py:329 ../apport/ui.py:456
#: ../apport/ui.py:459 ../apport/ui.py:660 ../apport/ui.py:1104
#: ../apport/ui.py:1270 ../apport/ui.py:1274
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:276
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1049
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:321
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:329
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:456
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:459
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:660
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1104
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1270
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1274
msgid "Invalid problem report"
msgstr ""

#: ../apport/ui.py:1036 ../apport/ui.py:1276
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1036
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1276
msgid "This problem report is damaged and cannot be processed."
msgstr ""

#. package does not exist
#: ../apport/ui.py:1039
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1039
msgid "The report belongs to a package that is not installed."
msgstr ""

#: ../apport/ui.py:1042
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1042
msgid "An error occurred while attempting to process this problem report:"
msgstr ""

#: ../apport/ui.py:322
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:322
msgid "You are not allowed to access this problem report."
msgstr ""

#: ../apport/ui.py:325
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:325
msgid "Error"
msgstr ""

#: ../apport/ui.py:326
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:326
msgid "There is not enough disk space available to process this report."
msgstr ""

#: ../apport/ui.py:410
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:410
msgid "No package specified"
msgstr ""

#: ../apport/ui.py:411
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:411
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""

#: ../apport/ui.py:434
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:434
msgid "Permission denied"
msgstr ""

#: ../apport/ui.py:435
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:435
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""

#: ../apport/ui.py:437
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:437
msgid "Invalid PID"
msgstr ""

#: ../apport/ui.py:438
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:438
msgid "The specified process ID does not belong to a program."
msgstr ""

#: ../apport/ui.py:457
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:457
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../apport/ui.py:460
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:460
#, python-format
msgid "Package %s does not exist"
msgstr ""

#: ../apport/ui.py:484 ../apport/ui.py:672 ../apport/ui.py:677
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:484
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:672
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:677
msgid "Cannot create report"
msgstr ""

#: ../apport/ui.py:499 ../apport/ui.py:545 ../apport/ui.py:562
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:499
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:545
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:562
msgid "Updating problem report"
msgstr ""

#: ../apport/ui.py:500
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:500
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""

#: ../apport/ui.py:509
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:509
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""

#: ../apport/ui.py:546 ../apport/ui.py:563
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:546
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:563
msgid "No additional information collected."
msgstr ""

#: ../apport/ui.py:614
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:614
msgid "What kind of problem do you want to report?"
msgstr ""

#: ../apport/ui.py:631
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:631
msgid "Unknown symptom"
msgstr ""

#: ../apport/ui.py:632
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:632
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr ""

#: ../apport/ui.py:663
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:663
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""

#: ../apport/ui.py:673 ../apport/ui.py:678
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:673
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:678
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../apport/ui.py:692
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:692
msgid "%prog <report number>"
msgstr ""

#: ../apport/ui.py:694
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:694
msgid "Specify package name."
msgstr ""

#: ../apport/ui.py:696 ../apport/ui.py:747
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:696
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:747
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../apport/ui.py:726
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:726
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../apport/ui.py:729
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:729
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../apport/ui.py:731
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:731
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../apport/ui.py:733
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:733
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../apport/ui.py:735
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:735
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:737
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:737
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../apport/ui.py:739
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:739
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:741
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:741
msgid "The provided pid is a hanging application."
msgstr ""

#: ../apport/ui.py:743
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:743
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../apport/ui.py:745
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:745
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../apport/ui.py:749
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:749
msgid "Print the Apport version number."
msgstr ""

#: ../apport/ui.py:889
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:889
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../apport/ui.py:890
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:890
msgid "Run gdb session"
msgstr ""

#: ../apport/ui.py:891
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:891
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:893
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:893
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../apport/ui.py:969 ../apport/ui.py:979
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:969
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:979
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""

#: ../apport/ui.py:994
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:994
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""

#: ../apport/ui.py:1105
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1105
msgid "Could not determine the package or source package name."
msgstr ""

#: ../apport/ui.py:1123
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1123
msgid "Unable to start web browser"
msgstr ""

#: ../apport/ui.py:1124
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1124
#, python-format
msgid "Unable to start web browser to open %s."
msgstr ""

#: ../apport/ui.py:1224
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1224
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""

#: ../apport/ui.py:1236
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1236
msgid "Network problem"
msgstr ""

#: ../apport/ui.py:1238
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1238
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""

#: ../apport/ui.py:1265
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1265
msgid "Memory exhaustion"
msgstr ""

#: ../apport/ui.py:1266
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1266
msgid "Your system does not have enough memory to process this crash report."
msgstr ""

#: ../apport/ui.py:1301
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1301
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""

#: ../apport/ui.py:1357 ../apport/ui.py:1364
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1357
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1364
msgid "Problem already known"
msgstr ""

#: ../apport/ui.py:1358
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1358
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""

#: ../apport/ui.py:1365
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1365
msgid "This problem was already reported to developers. Thank you!"
msgstr ""

#: ../bin/apport-cli.py:74 ../debian/tmp/usr/bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr ""

#: ../bin/apport-cli.py:81 ../debian/tmp/usr/bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr ""

#: ../bin/apport-cli.py:85 ../debian/tmp/usr/bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr ""

#: ../bin/apport-cli.py:148 ../debian/tmp/usr/bin/apport-cli.py:148
#, python-format
msgid "(%i bytes)"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:349 ../bin/apport-cli.py:150
#: ../kde/apport-kde.py:349 ../gtk/apport-gtk.py:142
#: ../debian/tmp/usr/bin/apport-cli.py:150
#: ../debian/tmp/usr/share/apport/apport-gtk.py:142
msgid "(binary data)"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:169 ../bin/apport-cli.py:178
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:404
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:429
#: ../kde/apport-kde.py:169 ../gtk/apport-gtk.py:177
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:286
#: ../debian/tmp/usr/bin/apport-cli.py:178
#: ../debian/tmp/usr/share/apport/apport-gtk.py:177
msgid "Send problem report to the developers?"
msgstr ""

#: ../bin/apport-cli.py:179 ../debian/tmp/usr/bin/apport-cli.py:179
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""

#: ../bin/apport-cli.py:182 ../debian/tmp/usr/bin/apport-cli.py:182
#, python-format
msgid "&Send report (%s)"
msgstr ""

#: ../bin/apport-cli.py:186 ../debian/tmp/usr/bin/apport-cli.py:186
msgid "&Examine locally"
msgstr ""

#: ../bin/apport-cli.py:190 ../debian/tmp/usr/bin/apport-cli.py:190
msgid "&View report"
msgstr ""

#: ../bin/apport-cli.py:191 ../debian/tmp/usr/bin/apport-cli.py:191
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""

#: ../bin/apport-cli.py:192 ../debian/tmp/usr/bin/apport-cli.py:192
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""

#: ../bin/apport-cli.py:194 ../bin/apport-cli.py:271 ../bin/apport-cli.py:303
#: ../bin/apport-cli.py:324 ../debian/tmp/usr/bin/apport-cli.py:194
#: ../debian/tmp/usr/bin/apport-cli.py:271
#: ../debian/tmp/usr/bin/apport-cli.py:303
#: ../debian/tmp/usr/bin/apport-cli.py:324
msgid "&Cancel"
msgstr ""

#: ../bin/apport-cli.py:222 ../debian/tmp/usr/bin/apport-cli.py:222
msgid "Problem report file:"
msgstr ""

#: ../bin/apport-cli.py:228 ../bin/apport-cli.py:233
#: ../debian/tmp/usr/bin/apport-cli.py:228
#: ../debian/tmp/usr/bin/apport-cli.py:233
msgid "&Confirm"
msgstr ""

#: ../bin/apport-cli.py:232 ../debian/tmp/usr/bin/apport-cli.py:232
#, python-format
msgid "Error: %s"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:394 ../bin/apport-cli.py:238
#: ../kde/apport-kde.py:394 ../debian/tmp/usr/bin/apport-cli.py:238
msgid "Collecting problem information"
msgstr ""

#: ../bin/apport-cli.py:239 ../debian/tmp/usr/bin/apport-cli.py:239
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:422 ../gtk/apport-gtk.ui.h:13
#: ../bin/apport-cli.py:251 ../kde/apport-kde.py:422
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
#: ../debian/tmp/usr/bin/apport-cli.py:251
msgid "Uploading problem information"
msgstr ""

#: ../bin/apport-cli.py:252 ../debian/tmp/usr/bin/apport-cli.py:252
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""

#: ../bin/apport-cli.py:302 ../debian/tmp/usr/bin/apport-cli.py:302
msgid "&Done"
msgstr ""

#: ../bin/apport-cli.py:308 ../debian/tmp/usr/bin/apport-cli.py:308
msgid "none"
msgstr ""

#: ../bin/apport-cli.py:309 ../debian/tmp/usr/bin/apport-cli.py:309
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr ""

#: ../bin/apport-cli.py:325 ../debian/tmp/usr/bin/apport-cli.py:325
msgid "Choices:"
msgstr ""

#: ../bin/apport-cli.py:339 ../debian/tmp/usr/bin/apport-cli.py:339
msgid "Path to file (Enter to cancel):"
msgstr ""

#: ../bin/apport-cli.py:345 ../debian/tmp/usr/bin/apport-cli.py:345
msgid "File does not exist."
msgstr ""

#: ../bin/apport-cli.py:347 ../debian/tmp/usr/bin/apport-cli.py:347
msgid "This is a directory."
msgstr ""

#: ../bin/apport-cli.py:353 ../debian/tmp/usr/bin/apport-cli.py:353
msgid "To continue, you must visit the following URL:"
msgstr ""

#: ../bin/apport-cli.py:355 ../debian/tmp/usr/bin/apport-cli.py:355
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""

#: ../bin/apport-cli.py:357 ../debian/tmp/usr/bin/apport-cli.py:357
msgid "Launch a browser now"
msgstr ""

#: ../bin/apport-cli.py:371 ../debian/tmp/usr/bin/apport-cli.py:371
msgid "No pending crash reports. Try --help for more information."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:73
#: ../data/apportcheckresume.py:73
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:75
#: ../data/apportcheckresume.py:75
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:80
#: ../data/apportcheckresume.py:80
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""

#: ../bin/apport-retrace.py:31 ../debian/tmp/usr/bin/apport-retrace.py:31
msgid "%prog [options] <apport problem report | crash ID>"
msgstr ""

#: ../bin/apport-retrace.py:33 ../debian/tmp/usr/bin/apport-retrace.py:33
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../bin/apport-retrace.py:35 ../debian/tmp/usr/bin/apport-retrace.py:35
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../bin/apport-retrace.py:37 ../debian/tmp/usr/bin/apport-retrace.py:37
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""

#: ../bin/apport-retrace.py:39 ../debian/tmp/usr/bin/apport-retrace.py:39
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Override report's CoreFile"
msgstr ""

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid "Override report's ExecutablePath"
msgstr ""

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid "Override report's ProcMaps"
msgstr ""

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Rebuild report's Package information"
msgstr ""

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-valgrind.py:66 ../bin/apport-retrace.py:59
#: ../debian/tmp/usr/bin/apport-retrace.py:59
#: ../debian/tmp/usr/bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../bin/apport-retrace.py:63 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../bin/apport-retrace.py:65 ../debian/tmp/usr/bin/apport-retrace.py:65
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../bin/apport-retrace.py:70 ../debian/tmp/usr/bin/apport-retrace.py:70
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""

#: ../bin/apport-retrace.py:76 ../debian/tmp/usr/bin/apport-retrace.py:76
msgid "You cannot use -C without -S. Stopping."
msgstr ""

#: ../bin/apport-retrace.py:80 ../debian/tmp/usr/bin/apport-retrace.py:80
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:114 ../debian/tmp/usr/bin/apport-retrace.py:114
msgid "OK to send these as attachments? [y/n]"
msgstr ""

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../kde/apport-kde-mime.desktop.in.h:1
msgid "Report a problem..."
msgstr ""

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../kde/apport-kde-mime.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr ""

#: ../debian/tmp/usr/share/apport/kernel_oops.py:30 ../data/kernel_oops.py:30
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../gtk/apport-gtk.py:157 ../debian/tmp/usr/share/apport/apport-gtk.py:157
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr ""

#: ../gtk/apport-gtk.py:160 ../debian/tmp/usr/share/apport/apport-gtk.py:160
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:183
#: ../debian/tmp/usr/share/apport/apport-kde.py:224
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:108
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:300
#: ../kde/apport-kde.py:183 ../kde/apport-kde.py:224 ../gtk/apport-gtk.py:165
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:110
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:254
#: ../debian/tmp/usr/share/apport/apport-gtk.py:165
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:177
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:412
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:437
#: ../kde/apport-kde.py:177 ../gtk/apport-gtk.py:186
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:292
#: ../debian/tmp/usr/share/apport/apport-gtk.py:186
msgid "Send"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:278 ../gtk/apport-gtk.ui.h:7
#: ../kde/apport-kde.py:278 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:573
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:573
msgid "Show Details"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:217
#: ../debian/tmp/usr/share/apport/apport-kde.py:230 ../gtk/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:144
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:157
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:192
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:310
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:350
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:479
#: ../kde/apport-kde.py:217 ../kde/apport-kde.py:230
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10 ../gtk/apport-gtk.py:216
#: ../gtk/apport-gtk.py:284 ../gtk/apport-gtk.py:303
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:141
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:153
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:186
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:262
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:332
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216
#: ../debian/tmp/usr/share/apport/apport-gtk.py:284
#: ../debian/tmp/usr/share/apport/apport-gtk.py:303
msgid "Continue"
msgstr ""

#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:276
#: ../gtk/apport-gtk.py:228 ../debian/tmp/usr/share/apport/apport-gtk.py:228
msgid "Force Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:221
#: ../debian/tmp/usr/share/apport/apport-kde.py:368
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:232
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:273
#: ../kde/apport-kde.py:221 ../kde/apport-kde.py:368 ../gtk/apport-gtk.py:229
#: ../gtk/apport-gtk.py:288
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:226
#: ../debian/tmp/usr/share/apport/apport-gtk.py:229
#: ../debian/tmp/usr/share/apport/apport-gtk.py:288
msgid "Relaunch"
msgstr ""

#: ../gtk/apport-gtk.py:238 ../debian/tmp/usr/share/apport/apport-gtk.py:238
#, python-format
msgid "The application %s has stopped responding."
msgstr ""

#: ../gtk/apport-gtk.py:242 ../debian/tmp/usr/share/apport/apport-gtk.py:242
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:191 ../kde/apport-kde.py:191
#: ../gtk/apport-gtk.py:257 ../debian/tmp/usr/share/apport/apport-gtk.py:257
#, python-format
msgid "Package: %s"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:197
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:137
#: ../kde/apport-kde.py:197 ../gtk/apport-gtk.py:264
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:136
#: ../debian/tmp/usr/share/apport/apport-gtk.py:264
msgid "Sorry, a problem occurred while installing software."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:204 ../kde/apport-kde.py:204
#: ../gtk/apport-gtk.py:273 ../gtk/apport-gtk.py:292
#: ../debian/tmp/usr/share/apport/apport-gtk.py:273
#: ../debian/tmp/usr/share/apport/apport-gtk.py:292
#, python-format
msgid "The application %s has experienced an internal error."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:208 ../kde/apport-kde.py:208
#: ../gtk/apport-gtk.py:276 ../debian/tmp/usr/share/apport/apport-gtk.py:276
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:220 ../gtk/apport-gtk.ui.h:9
#: ../kde/apport-kde.py:220 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
#: ../gtk/apport-gtk.py:287 ../debian/tmp/usr/share/apport/apport-gtk.py:287
msgid "Leave Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:227 ../gtk/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:302
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:342
#: ../kde/apport-kde.py:227 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
#: ../gtk/apport-gtk.py:300
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:256
#: ../debian/tmp/usr/share/apport/apport-gtk.py:300
msgid "If you notice further problems, try restarting the computer."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:231 ../kde/apport-kde.py:231
#: ../gtk/apport-gtk.py:304 ../debian/tmp/usr/share/apport/apport-gtk.py:304
msgid "Ignore future problems of this type"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:275 ../kde/apport-kde.py:275
#: ../gtk/apport-gtk.py:577 ../debian/tmp/usr/share/apport/apport-gtk.py:577
msgid "Hide Details"
msgstr ""

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr ""

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:301 ../kde/apport-kde.py:301
msgid "Username:"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:302 ../kde/apport-kde.py:302
msgid "Password:"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:393 ../kde/apport-kde.py:393
msgid "Collecting Problem Information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:395 ../kde/apport-kde.py:395
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:421 ../kde/apport-kde.py:421
msgid "Uploading Problem Information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:423 ../gtk/apport-gtk.ui.h:15
#: ../kde/apport-kde.py:423 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:457
#: ../debian/tmp/usr/share/apport/apport-kde.py:493 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:457 ../kde/apport-kde.py:493
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
msgid "Apport"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Crash report"
msgstr ""

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr ""

#: ../gtk/apport-gtk.ui.h:6 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr ""

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr ""

#: ../gtk/apport-gtk.ui.h:11 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""

#: ../gtk/apport-gtk.ui.h:14 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr ""

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr ""

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr ""

#: ../bin/apport-unpack.py:46 ../debian/tmp/usr/bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr ""
