# Finnish translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2012-10-01 11:58+0200\n"
"PO-Revision-Date: 2012-04-09 17:00+0000\n"
"Last-Translator: Jani Uusitalo <jani@mummila.net>\n"
"Language-Team: Finnish <fi@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2012-12-05 05:11+0000\n"
"X-Generator: Launchpad (build 16335)\n"
"Language: fi\n"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:105
#: ../apport/ui.py:105
msgid "This package does not seem to be installed correctly"
msgstr "Tätä pakettia ei ole asennettu oikein"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:109
#: ../apport/ui.py:109
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"Tämä ei ole virallinen %s-paketti. Poista kolmansien osapuolten paketit ja "
"yritä sitten uudelleen."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:126
#: ../apport/ui.py:126
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Järjestelmässä on asennettuna joidenkin pakettien vanhentuneita versiota. "
"Päivitä seuraavat paketit ja tarkista, uusiutuuko ongelma:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:232
#: ../apport/ui.py:232
msgid "unknown program"
msgstr "tuntematon sovellus"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:233
#: ../apport/ui.py:233
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Ikävä kyllä ohjelma \"%s\" sulkeutui yllättäen"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:235
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1237
#: ../apport/ui.py:235 ../apport/ui.py:1237
#, python-format
msgid "Problem in %s"
msgstr "Ongelma osan %s kanssa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:236
#: ../apport/ui.py:236
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Muistia ei ole vapaana tarpeeksi ongelman automaattiseen analysointiin ja "
"virheraportin lähettämiseen."

#. package does not exist
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:251
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:257
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:263
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:306
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:314
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:443
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:446
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:647
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1050
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1191
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1195
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1214
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1220
#: ../apport/ui.py:251 ../apport/ui.py:257 ../apport/ui.py:263
#: ../apport/ui.py:306 ../apport/ui.py:314 ../apport/ui.py:443
#: ../apport/ui.py:446 ../apport/ui.py:647 ../apport/ui.py:1050
#: ../apport/ui.py:1191 ../apport/ui.py:1195 ../apport/ui.py:1214
#: ../apport/ui.py:1220
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:268
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:285
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1052
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1072
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1083
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1094
msgid "Invalid problem report"
msgstr "Virheellinen ongelmaraportti"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:252
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1197
#: ../apport/ui.py:252 ../apport/ui.py:1197
msgid "This problem report is damaged and cannot be processed."
msgstr "Tämä ongelman raportti on vahingoittunut, eikä sitä voida käsitellä."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:258
#: ../apport/ui.py:258
msgid "The report belongs to a package that is not installed."
msgstr "Raportti liittyy pakettiin, jota ei ole asennettu."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:264
#: ../apport/ui.py:264
msgid "An error occurred while attempting to process this problem report:"
msgstr "Virhe käsiteltäessä ongelmaraporttia:"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:307
#: ../apport/ui.py:307
msgid "You are not allowed to access this problem report."
msgstr "Sinulla ei ole lukuoikeuksia tähän ongelmaraporttiin."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:310
#: ../apport/ui.py:310
msgid "Error"
msgstr "Virhe"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:311
#: ../apport/ui.py:311
msgid "There is not enough disk space available to process this report."
msgstr "Levyllä ei ole tarpeeksi tilaa raportin käsittelyyn."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:395
#: ../apport/ui.py:395
msgid "No package specified"
msgstr "Pakettia ei ole määritelty"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:396
#: ../apport/ui.py:396
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Paketti tai PID-tunniste on annettava. Katso lisätietoja käyttämällä "
"valitsinta --help."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:413
#: ../apport/ui.py:413
msgid "Invalid PID"
msgstr "PID-numero ei kelpaa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:414
#: ../apport/ui.py:414
msgid "The specified process ID does not belong to a program."
msgstr "Määritetty prosessin ID-numero ei kuulu kyseiselle ohjelmalle."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:422
#: ../apport/ui.py:422
msgid "Permission denied"
msgstr "Lupa evätty"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:423
#: ../apport/ui.py:423
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Kyseinen prosessi ei kuulu sinulle. Aja tämä ohjelma prosessin omistajana "
"tai pääkäyttäjänä."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:444
#: ../apport/ui.py:444
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Oirekomentosarja %s ei määritellyt vaikuttanutta pakettia"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:447
#: ../apport/ui.py:447
#, python-format
msgid "Package %s does not exist"
msgstr "Pakettia %s ei ole olemassa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:471
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:659
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:664
#: ../apport/ui.py:471 ../apport/ui.py:659 ../apport/ui.py:664
msgid "Cannot create report"
msgstr "Raporttia ei voida luoda"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:486
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:532
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:549
#: ../apport/ui.py:486 ../apport/ui.py:532 ../apport/ui.py:549
msgid "Updating problem report"
msgstr "Päivitetään ongelmaraporttia"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:487
#: ../apport/ui.py:487
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Et ole tämän ongelman raportoija tai ilmoittanut ongelmasta aikaisemmin; "
"ilmoitus on mahdollisesti kaksoiskopio tai se on jo suljettu aikaisemmin.\n"
"\n"
"Ole hyvä, ja luo uusi raportti käyttäen \"apport-bug\" määrittelyä."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:496
#: ../apport/ui.py:496
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Et ole tämän ongelman raportoija. On helpompaa merkitä ongelma jonkin toisen "
"samankaltaisen ongelman kopioksi, kuin siirtää kommenttisi ja liitteesi "
"täysin uuteen ongelmaraporttiin.\n"
"\n"
"Suosittelemme että lähetät uuden ongelmaraportin käyttäen \"apport-bug\" "
"määrittelyä ja lisäät tähän ongelmaan kommentin lisäämästäsi uudesta "
"ilmoituksesta.\n"
"\n"
"Haluatko todella jatkaa?"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:533
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:550
#: ../apport/ui.py:533 ../apport/ui.py:550
msgid "No additional information collected."
msgstr "Lisätietoja ei kerätty."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:601
#: ../apport/ui.py:601
msgid "What kind of problem do you want to report?"
msgstr "Millainen ongelma raportoidaan?"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:618
#: ../apport/ui.py:618
msgid "Unknown symptom"
msgstr "Tuntematon ongelma"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:619
#: ../apport/ui.py:619
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Ongelmaa \"%s\" ei tunnistettu."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:650
#: ../apport/ui.py:650
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Kun olet sulkenut tämän viestin napsauta sen sovelluksen ikkunaa, johon "
"liittyvän virheraportin haluat tehdä."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:660
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:665
#: ../apport/ui.py:660 ../apport/ui.py:665
msgid "xprop failed to determine process ID of the window"
msgstr "xprop ei onnistunut selvittämään ikkunaan ID-tunnistenumeroa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:679
#: ../apport/ui.py:679
msgid "%prog <report number>"
msgstr "%prog <raportin numero>"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:681
#: ../apport/ui.py:681
msgid "Specify package name."
msgstr "Määritä paketin nimi."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:683
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:734
#: ../apport/ui.py:683 ../apport/ui.py:734
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""
"Lisää raporttiin liittyvä tunniste. Tämä voidaan tehdä useampia kertoja."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:713
#: ../apport/ui.py:713
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [valinnat] [ongelma|pid|paketti|ohjelman "
"polku|.apport/.kaatumisraportti]"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:716
#: ../apport/ui.py:716
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Aloita ohjelmavirheiden kirjaustilassa. Se vaatii --package ja valinnaisen --"
"pid:n, tai vain --pid:n. Jos kumpaakaan ei anneta, näytä lista tunnetuista "
"oireista. (Epäsuora jos yksi argumentti on annettu.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:718
#: ../apport/ui.py:718
msgid "Click a window as a target for filing a problem report."
msgstr "Napsauta ikkunaa, johon liittyvän virheraportin haluat tehdä"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:720
#: ../apport/ui.py:720
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"Aloita ohjelmavirheiden päivitystilassa. Voi ottaa valinnaisen valitsimen --"
"package."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:722
#: ../apport/ui.py:722
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Arkistoi ohjelmavirheen raportti oireena. (Epäsuora jos oireen nimi on "
"annettu vain argumenttina.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:724
#: ../apport/ui.py:724
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Tarkenna paketin nimi --file-bug-tilassa. Tämä on valinnainen jos --pid on "
"määritetty. (Epäsuora jos paketin nimi on annettu vain argumenttina.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:726
#: ../apport/ui.py:726
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:728
#: ../apport/ui.py:728
msgid "The provided pid is a hanging application."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:730
#: ../apport/ui.py:730
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Raportoi kaatuminen annetusta .apport tai .crash-tiedostosta odottavien "
"sijaan kohdassa %s. (Epäsuora jos tiedosta on annettu vain argumenttina.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:732
#: ../apport/ui.py:732
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:736
#: ../apport/ui.py:736
msgid "Print the Apport version number."
msgstr "Tulosta Apport-versionumero."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:870
#: ../apport/ui.py:870
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:871
#: ../apport/ui.py:871
msgid "Run gdb session"
msgstr "Käynnistä gdb sessiossa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:872
#: ../apport/ui.py:872
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:874
#: ../apport/ui.py:874
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:947
#: ../apport/ui.py:947
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1051
#: ../apport/ui.py:1051
msgid "Could not determine the package or source package name."
msgstr "Paketin tai lähdekoodipaketin nimeä ei voi määrittää."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1069
#: ../apport/ui.py:1069
msgid "Unable to start web browser"
msgstr "Selaimen käynnistäminen epäonnistui"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1070
#: ../apport/ui.py:1070
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Verkkoselainta ei saatu käynnistettyä avattaessa sivua %s."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1145
#: ../apport/ui.py:1145
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "Ole hyvä ja syötä %s bugi raportointi järjestelmän kirjautumistiedot"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1157
#: ../apport/ui.py:1157
msgid "Network problem"
msgstr "Verkko-ongelma"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1159
#: ../apport/ui.py:1159
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Kaatumistietokantaan ei voi yhdistää. Tarkista Internet-yhteyden toimivuus."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1186
#: ../apport/ui.py:1186
msgid "Memory exhaustion"
msgstr "Muisti ei riitä"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1187
#: ../apport/ui.py:1187
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Järjestelmässäsi ei ole tarpeeksi muistia tämän kaatumisraportin käsittelyyn."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1210
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1219
#: ../apport/ui.py:1210 ../apport/ui.py:1219
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""
"Tämä ongelmaraportti kytkeytyy ohjelmaan, joka ei ole enää asennettu."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1240
#: ../apport/ui.py:1240
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Ongelman raportoiminen ei onnistunut:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1291
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1298
#: ../apport/ui.py:1291 ../apport/ui.py:1298
msgid "Problem already known"
msgstr "Ongelma on jo tiedossa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1292
#: ../apport/ui.py:1292
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Tämä ongelma raportoitiin jo virheraportissa, joka on näkyvissä selaimessa. "
"Tarkista, voisitko lisätä joitakin kehittäjiä auttavaa tietoa."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1299
#: ../apport/ui.py:1299
msgid "This problem was already reported to developers. Thank you!"
msgstr ""
"Tästä ongelmasta on jo ilmoitettu kehittäjille. Kiitos kuitenkin "
"auttamishalustasi!"

#: ../bin/apport-cli.py:73 ../debian/tmp/usr/bin/apport-cli.py:73
msgid "Press any key to continue..."
msgstr "Paina mitä tahansa näppäintä jatkaaksesi..."

#: ../bin/apport-cli.py:80 ../debian/tmp/usr/bin/apport-cli.py:80
msgid "What would you like to do? Your options are:"
msgstr "Kuinka haluat edetä? Vaihtoehdot ovat:"

#: ../bin/apport-cli.py:84 ../debian/tmp/usr/bin/apport-cli.py:84
#, python-format
msgid "Please choose (%s):"
msgstr "Ole hyvä ja valitse (%s):"

#: ../bin/apport-cli.py:144 ../debian/tmp/usr/bin/apport-cli.py:144
#, python-format
msgid "(%i bytes)"
msgstr "(%i tavua)"

#: ../debian/tmp/usr/share/apport/apport-kde.py:335 ../gtk/apport-gtk.py:138
#: ../bin/apport-cli.py:146 ../debian/tmp/usr/share/apport/apport-gtk.py:138
#: ../kde/apport-kde.py:335 ../debian/tmp/usr/bin/apport-cli.py:146
msgid "(binary data)"
msgstr "(binääritiedot)"

#: ../debian/tmp/usr/share/apport/apport-kde.py:162
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:395
#: ../gtk/apport-gtk.py:173
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:273
#: ../bin/apport-cli.py:174 ../debian/tmp/usr/share/apport/apport-gtk.py:173
#: ../kde/apport-kde.py:162 ../debian/tmp/usr/bin/apport-cli.py:174
msgid "Send problem report to the developers?"
msgstr "Lähetetäänkö raportti ongelmasta kehittäjille?"

#: ../bin/apport-cli.py:175 ../debian/tmp/usr/bin/apport-cli.py:175
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Kun raportti ongelmasta on lähetetty, ole ystävällinen ja täytä selaimeesi\n"
"automaattisesti aukeava lomake."

#: ../bin/apport-cli.py:178 ../debian/tmp/usr/bin/apport-cli.py:178
#, python-format
msgid "&Send report (%s)"
msgstr "&Lähetä raportti (%s)"

#: ../bin/apport-cli.py:182 ../debian/tmp/usr/bin/apport-cli.py:182
msgid "&Examine locally"
msgstr "&Tutki paikallisesti"

#: ../bin/apport-cli.py:186 ../debian/tmp/usr/bin/apport-cli.py:186
msgid "&View report"
msgstr "&Tarkastele raporttia"

#: ../bin/apport-cli.py:187 ../debian/tmp/usr/bin/apport-cli.py:187
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Säilytä raporttitiedosto myöhemmin lähetettäväksi tai muualle kopioitavaksi"

#: ../bin/apport-cli.py:188 ../debian/tmp/usr/bin/apport-cli.py:188
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Peru ja &jätä jatkossa huomiotta tämän ohjelmaversion kaatumiset"

#: ../bin/apport-cli.py:190 ../bin/apport-cli.py:267 ../bin/apport-cli.py:299
#: ../bin/apport-cli.py:320 ../debian/tmp/usr/bin/apport-cli.py:190
#: ../debian/tmp/usr/bin/apport-cli.py:267
#: ../debian/tmp/usr/bin/apport-cli.py:299
#: ../debian/tmp/usr/bin/apport-cli.py:320
msgid "&Cancel"
msgstr "&Peruuta"

#: ../bin/apport-cli.py:218 ../debian/tmp/usr/bin/apport-cli.py:218
msgid "Problem report file:"
msgstr "Ongelmaraporttitiedosto:"

#: ../bin/apport-cli.py:224 ../bin/apport-cli.py:229
#: ../debian/tmp/usr/bin/apport-cli.py:224
#: ../debian/tmp/usr/bin/apport-cli.py:229
msgid "&Confirm"
msgstr "&Vahvista"

#: ../bin/apport-cli.py:228 ../debian/tmp/usr/bin/apport-cli.py:228
#, python-format
msgid "Error: %s"
msgstr "Virhe: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:380 ../bin/apport-cli.py:234
#: ../kde/apport-kde.py:380 ../debian/tmp/usr/bin/apport-cli.py:234
msgid "Collecting problem information"
msgstr "Kerätään tietoja ongelmasta"

#: ../bin/apport-cli.py:235 ../debian/tmp/usr/bin/apport-cli.py:235
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Kerätyt tiedot voidaan lähettää kehittäjille ohjelman parantamiseksi.\n"
"Tähän voi mennä muutama minuutti."

#: ../debian/tmp/usr/share/apport/apport-kde.py:408 ../gtk/apport-gtk.ui.h:13
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../bin/apport-cli.py:247
#: ../kde/apport-kde.py:408 ../debian/tmp/usr/bin/apport-cli.py:247
msgid "Uploading problem information"
msgstr "Lähetetään tiedot ongelmasta"

#: ../bin/apport-cli.py:248 ../debian/tmp/usr/bin/apport-cli.py:248
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Kerätyt tiedot lähetetään virheseurantajärjestelmään.\n"
"Tähän voi mennä muutama minuutti."

#: ../bin/apport-cli.py:298 ../debian/tmp/usr/bin/apport-cli.py:298
msgid "&Done"
msgstr "&Valmis"

#: ../bin/apport-cli.py:304 ../debian/tmp/usr/bin/apport-cli.py:304
msgid "none"
msgstr "ei mitään"

#: ../bin/apport-cli.py:305 ../debian/tmp/usr/bin/apport-cli.py:305
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Valittu: %s. Useita valintoja:"

#: ../bin/apport-cli.py:321 ../debian/tmp/usr/bin/apport-cli.py:321
msgid "Choices:"
msgstr "Valinnat:"

#: ../bin/apport-cli.py:335 ../debian/tmp/usr/bin/apport-cli.py:335
msgid "Path to file (Enter to cancel):"
msgstr "Polku tiedostoon (Enter peruu):"

#: ../bin/apport-cli.py:341 ../debian/tmp/usr/bin/apport-cli.py:341
msgid "File does not exist."
msgstr "Tiedostoa ei ole olemassa."

#: ../bin/apport-cli.py:343 ../debian/tmp/usr/bin/apport-cli.py:343
msgid "This is a directory."
msgstr "Tämä on hakemisto."

#: ../bin/apport-cli.py:349 ../debian/tmp/usr/bin/apport-cli.py:349
msgid "To continue, you must visit the following URL:"
msgstr "Jatkaaksesi sinun tulee käydä seuraavassa URL-osoitteessa:"

#: ../bin/apport-cli.py:351 ../debian/tmp/usr/bin/apport-cli.py:351
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Voit nyt käynnistää selaimen tai kopioida tämän URL-osoitteen selaimeen "
"toisella tietokoneella."

#: ../bin/apport-cli.py:353 ../debian/tmp/usr/bin/apport-cli.py:353
msgid "Launch a browser now"
msgstr "Käynnistä selain nyt"

#: ../bin/apport-cli.py:367 ../debian/tmp/usr/bin/apport-cli.py:367
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"Ei odottavia kaatumisraportteja. Kokeile --help saadaksesi lisäinformaatiota."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""
"Tämä tapahtui viimeisen keskeytyksen aikana ja esti sitä jatkamasta "
"asianmukaisesti."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""
"Tämä tapahtui viimeisen horrostilan aikana ja esti sitä jatkamasta "
"asianmukaisesti."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Aloitettu ajo jumiutui erittäin lähellä loppua ja tulee ilmestymään "
"suorittuakseen loppuun normaalisti."

#: ../bin/apport-retrace.py:40 ../debian/tmp/usr/bin/apport-retrace.py:40
msgid "%prog [options] <apport problem report | crash ID>"
msgstr "%prog [valinnat] <tasaa ongelmaraportti | kaatumistunniste>"

#: ../bin/apport-retrace.py:42 ../debian/tmp/usr/bin/apport-retrace.py:42
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""
"Älä laita uusia jäljityksiä raporttiin, mutta kirjoita ne stdout:iin."

#: ../bin/apport-retrace.py:44 ../debian/tmp/usr/bin/apport-retrace.py:44
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Aloita interaktiiviinen gdb-istunto raportin ydinvedoksen kanssa (-o jättää "
"huomioimatta; ei kirjoita raporttia)"

#: ../bin/apport-retrace.py:46 ../debian/tmp/usr/bin/apport-retrace.py:46
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Kirjoita muokattu raportti annetulle tiedostolle alkuperäisen raportin "
"muuttamisen sijaan."

#: ../bin/apport-retrace.py:48 ../debian/tmp/usr/bin/apport-retrace.py:48
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Poista muistivedos raportista pinojäljityksen elvyttämisen jälkeen"

#: ../bin/apport-retrace.py:50 ../debian/tmp/usr/bin/apport-retrace.py:50
msgid "Override report's CoreFile"
msgstr "Korvaa raportin CoreFile"

#: ../bin/apport-retrace.py:52 ../debian/tmp/usr/bin/apport-retrace.py:52
msgid "Override report's ExecutablePath"
msgstr "Korvaa raportin ExecutablePath"

#: ../bin/apport-retrace.py:54 ../debian/tmp/usr/bin/apport-retrace.py:54
msgid "Override report's ProcMaps"
msgstr "Korvaa raportin ProcMaps"

#: ../bin/apport-retrace.py:56 ../debian/tmp/usr/bin/apport-retrace.py:56
msgid "Rebuild report's Package information"
msgstr "Rakenna raportin Paketti-informaatio uudelleen"

#: ../bin/apport-retrace.py:58 ../debian/tmp/usr/bin/apport-retrace.py:58
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../bin/apport-retrace.py:60 ../debian/tmp/usr/bin/apport-retrace.py:60
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-retrace.py:62 ../debian/tmp/usr/bin/apport-retrace.py:62
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../bin/apport-retrace.py:64 ../debian/tmp/usr/bin/apport-retrace.py:64
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../bin/apport-retrace.py:66 ../debian/tmp/usr/bin/apport-retrace.py:66
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-retrace.py:68 ../debian/tmp/usr/bin/apport-retrace.py:68
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-retrace.py:70 ../debian/tmp/usr/bin/apport-retrace.py:70
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Polku tiedostoon kaatumistietokannan todentamistietojen kanssa. Tätä "
"käytetään määritettäessä kaatumistunnistetta ladattaessa jäljitettyä "
"pinojälkiä. (vain jos yhtäkään seuraavista ei ole määritetty: -g, -o ja -s)"

#: ../bin/apport-retrace.py:72 ../debian/tmp/usr/bin/apport-retrace.py:72
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Näytä seuratut pinojäljet ja pyydä vahvistusta ennen niiden lähettämistä "
"kaatumistietokantaan."

#: ../bin/apport-retrace.py:74 ../debian/tmp/usr/bin/apport-retrace.py:74
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Polku jäljennös-sqlite-tietokantaan (oletus: ei jälkennöksen tarkistusta)"

#: ../bin/apport-retrace.py:79 ../debian/tmp/usr/bin/apport-retrace.py:79
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""
"virheellinen lukumäärä argumentteja; käytä --help:iä saadaksesi lyhyesti apua"

#: ../bin/apport-retrace.py:83 ../debian/tmp/usr/bin/apport-retrace.py:83
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""
"sinun tarvitsee tehdä joko paikallinen operaatio (-s, -g, -o) tai toimittaa "
"varmennustiedosto (--auth); katso --help saadaksesi lyhyesti apua"

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:117 ../debian/tmp/usr/bin/apport-retrace.py:117
msgid "OK to send these as attachments? [y/n]"
msgstr "Sopiiko näiden lähettäminen liitteinä? [y/n] (y=kyllä, n=ei)"

#: ../gtk/apport-gtk-mime.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1 ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Raportoi ongelma"

#: ../gtk/apport-gtk-mime.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2 ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Raportoi toimintahäiriöstä sovelluksen kehittäjille"

#: ../debian/tmp/usr/share/apport/kernel_oops.py:28 ../data/kernel_oops.py:28
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"Järjestelmästäsi saattaa tulla epävakaa ja se saattaa tarvita "
"uudelleenkäynnistystä."

#: ../gtk/apport-gtk.py:153 ../debian/tmp/usr/share/apport/apport-gtk.py:153
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Valitettavasti sovellus %s pysähtyi odottamatta."

#: ../gtk/apport-gtk.py:156 ../debian/tmp/usr/share/apport/apport-gtk.py:156
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Valitettavasti %s sulkeutui odottamatta."

#: ../debian/tmp/usr/share/apport/apport-kde.py:176
#: ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:108
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:291
#: ../gtk/apport-gtk.py:161
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:106
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:241
#: ../debian/tmp/usr/share/apport/apport-gtk.py:161 ../kde/apport-kde.py:176
#: ../kde/apport-kde.py:214
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Valitettavasti %s kohtasi sisäisen virheen."

#: ../debian/tmp/usr/share/apport/apport-kde.py:170
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:403
#: ../gtk/apport-gtk.py:182
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:279
#: ../debian/tmp/usr/share/apport/apport-gtk.py:182 ../kde/apport-kde.py:170
msgid "Send"
msgstr "Lähetä"

#: ../debian/tmp/usr/share/apport/apport-kde.py:268 ../gtk/apport-gtk.ui.h:7
#: ../gtk/apport-gtk.py:200 ../gtk/apport-gtk.py:567
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.py:200
#: ../debian/tmp/usr/share/apport/apport-gtk.py:567 ../kde/apport-kde.py:268
msgid "Show Details"
msgstr "Näytä tiedot"

#: ../debian/tmp/usr/share/apport/apport-kde.py:211
#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:144
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:183
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:301
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:341
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:445
#: ../gtk/apport-gtk.ui.h:10 ../gtk/apport-gtk.py:212 ../gtk/apport-gtk.py:282
#: ../gtk/apport-gtk.py:297 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:111
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:137
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:173
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:249
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:319
#: ../debian/tmp/usr/share/apport/apport-gtk.py:212
#: ../debian/tmp/usr/share/apport/apport-gtk.py:282
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297 ../kde/apport-kde.py:211
#: ../kde/apport-kde.py:220
msgid "Continue"
msgstr "Jatka"

#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:267
#: ../gtk/apport-gtk.py:224 ../debian/tmp/usr/share/apport/apport-gtk.py:224
msgid "Force Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:208
#: ../debian/tmp/usr/share/apport/apport-kde.py:354
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:223
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:264
#: ../gtk/apport-gtk.py:225 ../gtk/apport-gtk.py:279
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:213
#: ../debian/tmp/usr/share/apport/apport-gtk.py:225
#: ../debian/tmp/usr/share/apport/apport-gtk.py:279 ../kde/apport-kde.py:208
#: ../kde/apport-kde.py:354
msgid "Relaunch"
msgstr "Käynnistä uudelleen"

#: ../gtk/apport-gtk.py:234 ../debian/tmp/usr/share/apport/apport-gtk.py:234
#, python-format
msgid "The application %s has stopped responding."
msgstr "Sovellus \"%s\" ei vastaa."

#: ../gtk/apport-gtk.py:238 ../debian/tmp/usr/share/apport/apport-gtk.py:238
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Ohjelma \"%s\" ei vastaa."

#: ../debian/tmp/usr/share/apport/apport-kde.py:184 ../gtk/apport-gtk.py:253
#: ../debian/tmp/usr/share/apport/apport-gtk.py:253 ../kde/apport-kde.py:184
#, python-format
msgid "Package: %s"
msgstr "Paketti: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:190
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:137
#: ../gtk/apport-gtk.py:260
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:132
#: ../debian/tmp/usr/share/apport/apport-gtk.py:260 ../kde/apport-kde.py:190
msgid "Sorry, a problem occurred while installing software."
msgstr "Valitettavasti ohjelmistoja asennettaessa ilmeni ongelma."

#: ../debian/tmp/usr/share/apport/apport-kde.py:197 ../gtk/apport-gtk.py:269
#: ../gtk/apport-gtk.py:286 ../debian/tmp/usr/share/apport/apport-gtk.py:269
#: ../debian/tmp/usr/share/apport/apport-gtk.py:286 ../kde/apport-kde.py:197
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "Sovellus %s kohtasi sisäisen virheen."

#: ../debian/tmp/usr/share/apport/apport-kde.py:201 ../gtk/apport-gtk.py:272
#: ../debian/tmp/usr/share/apport/apport-gtk.py:272 ../kde/apport-kde.py:201
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Sovellus %s sulkeutui yllättäen."

#: ../debian/tmp/usr/share/apport/apport-kde.py:207 ../gtk/apport-gtk.ui.h:9
#: ../gtk/apport-gtk.py:278 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
#: ../debian/tmp/usr/share/apport/apport-gtk.py:278 ../kde/apport-kde.py:207
msgid "Leave Closed"
msgstr "Sulje sovellus"

#: ../debian/tmp/usr/share/apport/apport-kde.py:217
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:293
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:333
#: ../gtk/apport-gtk.ui.h:4 ../gtk/apport-gtk.py:294
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:243
#: ../debian/tmp/usr/share/apport/apport-gtk.py:294 ../kde/apport-kde.py:217
msgid "If you notice further problems, try restarting the computer."
msgstr "Jos ongelmat jatkuvat, käynnistä tietokone uudelleen."

#: ../debian/tmp/usr/share/apport/apport-kde.py:221 ../gtk/apport-gtk.py:298
#: ../debian/tmp/usr/share/apport/apport-gtk.py:298 ../kde/apport-kde.py:221
msgid "Ignore future problems of this type"
msgstr "Jätä huomiotta tulevat vastaavanlaiset ongelmat"

#: ../debian/tmp/usr/share/apport/apport-kde.py:265 ../gtk/apport-gtk.py:571
#: ../debian/tmp/usr/share/apport/apport-gtk.py:571 ../kde/apport-kde.py:265
msgid "Hide Details"
msgstr "Piilota tiedot"

#: ../debian/tmp/usr/share/apport/apport-kde.py:291 ../kde/apport-kde.py:291
msgid "Username:"
msgstr "Käyttäjätunnus"

#: ../debian/tmp/usr/share/apport/apport-kde.py:292 ../kde/apport-kde.py:292
msgid "Password:"
msgstr "Salasana:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:379 ../kde/apport-kde.py:379
msgid "Collecting Problem Information"
msgstr "Kerätään tietoja ongelmasta"

#: ../debian/tmp/usr/share/apport/apport-kde.py:381 ../kde/apport-kde.py:381
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Kerätty tieto voidaan lähettää kehittäjille ohjelmiston parantamiseksi. Tämä "
"voi kestää muutamia minuutteja."

#: ../debian/tmp/usr/share/apport/apport-kde.py:407 ../kde/apport-kde.py:407
msgid "Uploading Problem Information"
msgstr "Lähetetään tiedot ongelmasta"

#: ../debian/tmp/usr/share/apport/apport-kde.py:409 ../gtk/apport-gtk.ui.h:15
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../kde/apport-kde.py:409
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Kerättyjä tietoja lähetetään vianseurantajärjestelmään. Tämä saattaa kestää "
"muutamia minuutteja."

#: ../debian/tmp/usr/share/apport/apport-kde.py:443
#: ../debian/tmp/usr/share/apport/apport-kde.py:479 ../gtk/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1 ../kde/apport-kde.py:443
#: ../kde/apport-kde.py:479
msgid "Apport"
msgstr "Apport"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Kerää järjestelmätiedot"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Vikailmoitukseen tarvittavien järjestelmätietojen kerääminen vaatii "
"tunnistautumisen"

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Crash report"
msgstr "Ohjelmisto lopetti toimintansa"

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Valitettavasti havaittiin sisäinen virhe.</b></big>"

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr "Auta kehittäjiä korjaamaan tämä ongelma lähettämällä vikailmoitus"

#: ../gtk/apport-gtk.ui.h:6 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr "Älä huomioi tämän ohjelmiston kaatumisia jatkossa"

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr "_Tutki paikallisesti"

#: ../gtk/apport-gtk.ui.h:11 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Kerätään tietoja ongelmasta</b></big>"

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr "Kerätään tietoja ongelman korjaamisen helpottamiseksi."

#: ../gtk/apport-gtk.ui.h:14 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Lähetetään tietoja ongelmasta</b></big>"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport-kaatumistiedosto"

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Käyttö: %s <raportti> <kohdehakemisto>"

#: ../debian/tmp/usr/bin/apport-unpack.py:46 ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr "Kohdehakemisto on jo olemassa, eikä ole tyhjä."

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "Voit auttaa kehittäjiä korjaaman ongelman ilmoittamalla siitä."

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "Paketin \"%s\" asennus tai päivitys epäonnistui."

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Täydellinen raportti (suositus; %s)"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Lähetetäänkö ongelmaraportti sovelluksen kehittäjille?</b></big>\n"
#~ "\n"
#~ "Ole hyvä ja täytä automaattisesti selaimeen auennut lomake, kun "
#~ "ongelmaraportti on lähetetty."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "Jos et tehnyt mitään luottamuksellista (syöttänyt salasanoja tai muita "
#~ "henkilökohtaisia tietoja), voit auttaa kehittämään ohjelmaa raportoimalla "
#~ "ongelmasta."

#, python-format
#~ msgid "Sorry, %s closed unexpectedly"
#~ msgstr "Ikävä kyllä %s sulkeutui yllättäen"

#~ msgid "Application problem"
#~ msgstr "Ongelma sovelluksessa"

#~ msgid "&Details..."
#~ msgstr "&Yksityiskohdat..."

#~ msgid "_Send Report"
#~ msgstr "_Lähetä raportti"

#~ msgid "Generic error"
#~ msgstr "Yleinen virhe"

#~ msgid ""
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "Kun raportti on lähetetty, ole hyvä ja täytä selaimeesi automaattisesti "
#~ "aukeava lomake."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Jos et ollut tekemässä mitään luottamuksellista (kuten syöttänyt salasanoja "
#~ "tai muuta\n"
#~ "henkilökohtaista tietoa), voit auttaa ohjelman kehittämisessä raportoimalla\n"
#~ "ongelman."

#~ msgid "Restart _Program"
#~ msgstr "Uudelleenkäynnistä _ohjelma"

#, python-format
#~ msgid "Sorry, the package \"%s\" failed to install or upgrade."
#~ msgstr "Ikävä kyllä paketin \"%s\" asennus tai päivitys epäonnistui."

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">Paketin \"%s\" asennus tai päivitys "
#~ "epäonnistui.</span>"

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Lähetä täydellinen raportti (suositeltavaa; %s)"

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Pelkistetty raportti (hidas Internet-yhteys; %s)"

#, python-format
#~ msgid "Sorry, %s closed unexpectedly."
#~ msgstr "Ikävä kyllä %s sulkeutui yllättäen."

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Jätä tämän ohjelmaversion kaatumiset huomiotta jatkossa"

#~ msgid "Restart &Program"
#~ msgstr "Käynnistä &ohjelma uudelleen"

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Lähetä &suppea raportti (hitaille Internet-yhteyksille; %s)"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "Tämä poistaa joitain isoimpia osuuksia raportista. Osuudet ovat hyödyllisiä "
#~ "ohjelman kehittäjille ongelman selvittämisessä mutta et välttämättä halua "
#~ "odottaa niiden lähettämistä, jos Internet-yhteytesi on hidas."

#~ msgid "&Report Problem..."
#~ msgstr "&Raportoi ongelma..."

#~ msgid "_Report Problem..."
#~ msgstr "_Raportoi ongelma..."

#~ msgid "&Send"
#~ msgstr "&Lähetä"

#~ msgid "Kernel problem"
#~ msgstr "Ongelma käyttöjärjestelmän ytimessä"

#~ msgid "&Ignore future crashes of this program version"
#~ msgstr "Älä huomioi tämän ohjelmaversion kaatumisia jatkossa"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr "Voi auttaa kehittäjiä korjaamaan ongelman raportoimalla ongelmasta."

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "Tämä ei ole alkuperäinen %s-paketti"

#, python-format
#~ msgid "Sorry, the program \"%s\" closed unexpectedly."
#~ msgstr "Ikävä kyllä ohjelma \"%s\" sulkeutui yllättäen."

#~ msgid "Content of the report"
#~ msgstr "Raportin sisältö"

#~ msgid "Package problem"
#~ msgstr "Ongelma paketissa"

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "Järjestelmässä tapahtui vakava ydinongelma."

#~ msgid "Send this data to the developers?"
#~ msgstr "Lähetetäänkö nämä tiedot kehittäjille?"

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s sulkeutui yllättäen %s %s."

#, python-format
#~ msgid "Sorry, the application %s has closed unexpectedly."
#~ msgstr "Valitettavasti sovellus %s sulkeutui odottamatta."
