# Finnish translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-05-21 12:15+0200\n"
"PO-Revision-Date: 2012-04-09 17:00+0000\n"
"Last-Translator: Jani Uusitalo <jani@mummila.net>\n"
"Language-Team: Finnish <fi@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-07-30 04:32+0000\n"
"X-Generator: Launchpad (build 16700)\n"
"Language: fi\n"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:124
#: ../apport/ui.py:124
msgid "This package does not seem to be installed correctly"
msgstr "Tätä pakettia ei ole asennettu oikein"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:128
#: ../apport/ui.py:128
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"Tämä ei ole virallinen %s-paketti. Poista kolmansien osapuolten paketit ja "
"yritä sitten uudelleen."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:145
#: ../apport/ui.py:145
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Järjestelmässä on asennettuna joidenkin pakettien vanhentuneita versiota. "
"Päivitä seuraavat paketit ja tarkista, uusiutuuko ongelma:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:251
#: ../apport/ui.py:251
msgid "unknown program"
msgstr "tuntematon sovellus"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:252
#: ../apport/ui.py:252
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Ikävä kyllä ohjelma \"%s\" sulkeutui yllättäen"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:254
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1256
#: ../apport/ui.py:254 ../apport/ui.py:1256
#, python-format
msgid "Problem in %s"
msgstr "Ongelma osan %s kanssa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:255
#: ../apport/ui.py:255
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Muistia ei ole vapaana tarpeeksi ongelman automaattiseen analysointiin ja "
"virheraportin lähettämiseen."

#. package does not exist
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:268
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:285
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1052
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1072
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1083
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1094
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:270
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:276
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:282
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:325
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:333
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:462
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:465
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:666
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1069
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1210
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1214
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1233
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1239
#: ../apport/ui.py:270 ../apport/ui.py:276 ../apport/ui.py:282
#: ../apport/ui.py:325 ../apport/ui.py:333 ../apport/ui.py:462
#: ../apport/ui.py:465 ../apport/ui.py:666 ../apport/ui.py:1069
#: ../apport/ui.py:1210 ../apport/ui.py:1214 ../apport/ui.py:1233
#: ../apport/ui.py:1239
msgid "Invalid problem report"
msgstr "Virheellinen ongelmaraportti"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:271
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1216
#: ../apport/ui.py:271 ../apport/ui.py:1216
msgid "This problem report is damaged and cannot be processed."
msgstr "Tämä ongelman raportti on vahingoittunut, eikä sitä voida käsitellä."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:277
#: ../apport/ui.py:277
msgid "The report belongs to a package that is not installed."
msgstr "Raportti liittyy pakettiin, jota ei ole asennettu."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:283
#: ../apport/ui.py:283
msgid "An error occurred while attempting to process this problem report:"
msgstr "Virhe käsiteltäessä ongelmaraporttia:"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:326
#: ../apport/ui.py:326
msgid "You are not allowed to access this problem report."
msgstr "Sinulla ei ole lukuoikeuksia tähän ongelmaraporttiin."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:329
#: ../apport/ui.py:329
msgid "Error"
msgstr "Virhe"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:330
#: ../apport/ui.py:330
msgid "There is not enough disk space available to process this report."
msgstr "Levyllä ei ole tarpeeksi tilaa raportin käsittelyyn."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:414
#: ../apport/ui.py:414
msgid "No package specified"
msgstr "Pakettia ei ole määritelty"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:415
#: ../apport/ui.py:415
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Paketti tai PID-tunniste on annettava. Katso lisätietoja käyttämällä "
"valitsinta --help."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:432
#: ../apport/ui.py:432
msgid "Invalid PID"
msgstr "PID-numero ei kelpaa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:433
#: ../apport/ui.py:433
msgid "The specified process ID does not belong to a program."
msgstr "Määritetty prosessin ID-numero ei kuulu kyseiselle ohjelmalle."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:441
#: ../apport/ui.py:441
msgid "Permission denied"
msgstr "Lupa evätty"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:442
#: ../apport/ui.py:442
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Kyseinen prosessi ei kuulu sinulle. Aja tämä ohjelma prosessin omistajana "
"tai pääkäyttäjänä."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:463
#: ../apport/ui.py:463
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Oirekomentosarja %s ei määritellyt vaikuttanutta pakettia"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:466
#: ../apport/ui.py:466
#, python-format
msgid "Package %s does not exist"
msgstr "Pakettia %s ei ole olemassa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:490
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:678
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:683
#: ../apport/ui.py:490 ../apport/ui.py:678 ../apport/ui.py:683
msgid "Cannot create report"
msgstr "Raporttia ei voida luoda"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:505
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:551
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:568
#: ../apport/ui.py:505 ../apport/ui.py:551 ../apport/ui.py:568
msgid "Updating problem report"
msgstr "Päivitetään ongelmaraporttia"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:506
#: ../apport/ui.py:506
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Et ole tämän ongelman raportoija tai ilmoittanut ongelmasta aikaisemmin; "
"ilmoitus on mahdollisesti kaksoiskopio tai se on jo suljettu aikaisemmin.\n"
"\n"
"Ole hyvä, ja luo uusi raportti käyttäen \"apport-bug\" määrittelyä."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:515
#: ../apport/ui.py:515
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Et ole tämän ongelman raportoija. On helpompaa merkitä ongelma jonkin toisen "
"samankaltaisen ongelman kopioksi, kuin siirtää kommenttisi ja liitteesi "
"täysin uuteen ongelmaraporttiin.\n"
"\n"
"Suosittelemme että lähetät uuden ongelmaraportin käyttäen \"apport-bug\" "
"määrittelyä ja lisäät tähän ongelmaan kommentin lisäämästäsi uudesta "
"ilmoituksesta.\n"
"\n"
"Haluatko todella jatkaa?"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:569
#: ../apport/ui.py:552 ../apport/ui.py:569
msgid "No additional information collected."
msgstr "Lisätietoja ei kerätty."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:620
#: ../apport/ui.py:620
msgid "What kind of problem do you want to report?"
msgstr "Millainen ongelma raportoidaan?"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:637
#: ../apport/ui.py:637
msgid "Unknown symptom"
msgstr "Tuntematon ongelma"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:638
#: ../apport/ui.py:638
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Ongelmaa \"%s\" ei tunnistettu."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:669
#: ../apport/ui.py:669
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Kun olet sulkenut tämän viestin napsauta sen sovelluksen ikkunaa, johon "
"liittyvän virheraportin haluat tehdä."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:679
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:684
#: ../apport/ui.py:679 ../apport/ui.py:684
msgid "xprop failed to determine process ID of the window"
msgstr "xprop ei onnistunut selvittämään ikkunaan ID-tunnistenumeroa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:698
#: ../apport/ui.py:698
msgid "%prog <report number>"
msgstr "%prog <raportin numero>"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:700
#: ../apport/ui.py:700
msgid "Specify package name."
msgstr "Määritä paketin nimi."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:702
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:753
#: ../apport/ui.py:702 ../apport/ui.py:753
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""
"Lisää raporttiin liittyvä tunniste. Tämä voidaan tehdä useampia kertoja."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:732
#: ../apport/ui.py:732
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [valinnat] [ongelma|pid|paketti|ohjelman "
"polku|.apport/.kaatumisraportti]"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:735
#: ../apport/ui.py:735
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Aloita ohjelmavirheiden kirjaustilassa. Se vaatii --package ja valinnaisen --"
"pid:n, tai vain --pid:n. Jos kumpaakaan ei anneta, näytä lista tunnetuista "
"oireista. (Epäsuora jos yksi argumentti on annettu.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:737
#: ../apport/ui.py:737
msgid "Click a window as a target for filing a problem report."
msgstr "Napsauta ikkunaa, johon liittyvän virheraportin haluat tehdä"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:739
#: ../apport/ui.py:739
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"Aloita ohjelmavirheiden päivitystilassa. Voi ottaa valinnaisen valitsimen --"
"package."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:741
#: ../apport/ui.py:741
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Arkistoi ohjelmavirheen raportti oireena. (Epäsuora jos oireen nimi on "
"annettu vain argumenttina.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:743
#: ../apport/ui.py:743
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Tarkenna paketin nimi --file-bug-tilassa. Tämä on valinnainen jos --pid on "
"määritetty. (Epäsuora jos paketin nimi on annettu vain argumenttina.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:745
#: ../apport/ui.py:745
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:747
#: ../apport/ui.py:747
msgid "The provided pid is a hanging application."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:749
#: ../apport/ui.py:749
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Raportoi kaatuminen annetusta .apport tai .crash-tiedostosta odottavien "
"sijaan kohdassa %s. (Epäsuora jos tiedosta on annettu vain argumenttina.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:751
#: ../apport/ui.py:751
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:755
#: ../apport/ui.py:755
msgid "Print the Apport version number."
msgstr "Tulosta Apport-versionumero."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:889
#: ../apport/ui.py:889
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:890
#: ../apport/ui.py:890
msgid "Run gdb session"
msgstr "Käynnistä gdb sessiossa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:891
#: ../apport/ui.py:891
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:893
#: ../apport/ui.py:893
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:966
#: ../apport/ui.py:966
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1070
#: ../apport/ui.py:1070
msgid "Could not determine the package or source package name."
msgstr "Paketin tai lähdekoodipaketin nimeä ei voi määrittää."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1088
#: ../apport/ui.py:1088
msgid "Unable to start web browser"
msgstr "Selaimen käynnistäminen epäonnistui"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1089
#: ../apport/ui.py:1089
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Verkkoselainta ei saatu käynnistettyä avattaessa sivua %s."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1164
#: ../apport/ui.py:1164
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "Ole hyvä ja syötä %s bugi raportointi järjestelmän kirjautumistiedot"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1176
#: ../apport/ui.py:1176
msgid "Network problem"
msgstr "Verkko-ongelma"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1178
#: ../apport/ui.py:1178
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Kaatumistietokantaan ei voi yhdistää. Tarkista Internet-yhteyden toimivuus."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1205
#: ../apport/ui.py:1205
msgid "Memory exhaustion"
msgstr "Muisti ei riitä"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1206
#: ../apport/ui.py:1206
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Järjestelmässäsi ei ole tarpeeksi muistia tämän kaatumisraportin käsittelyyn."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1229
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1238
#: ../apport/ui.py:1229 ../apport/ui.py:1238
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""
"Tämä ongelmaraportti kytkeytyy ohjelmaan, joka ei ole enää asennettu."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1259
#: ../apport/ui.py:1259
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Ongelman raportoiminen ei onnistunut:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1315
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1322
#: ../apport/ui.py:1315 ../apport/ui.py:1322
msgid "Problem already known"
msgstr "Ongelma on jo tiedossa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1316
#: ../apport/ui.py:1316
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Tämä ongelma raportoitiin jo virheraportissa, joka on näkyvissä selaimessa. "
"Tarkista, voisitko lisätä joitakin kehittäjiä auttavaa tietoa."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1323
#: ../apport/ui.py:1323
msgid "This problem was already reported to developers. Thank you!"
msgstr ""
"Tästä ongelmasta on jo ilmoitettu kehittäjille. Kiitos kuitenkin "
"auttamishalustasi!"

#: ../debian/tmp/usr/bin/apport-cli.py:74 ../bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr "Paina mitä tahansa näppäintä jatkaaksesi..."

#: ../debian/tmp/usr/bin/apport-cli.py:81 ../bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr "Kuinka haluat edetä? Vaihtoehdot ovat:"

#: ../debian/tmp/usr/bin/apport-cli.py:85 ../bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr "Ole hyvä ja valitse (%s):"

#: ../debian/tmp/usr/bin/apport-cli.py:145 ../bin/apport-cli.py:145
#, python-format
msgid "(%i bytes)"
msgstr "(%i tavua)"

#: ../gtk/apport-gtk.py:138 ../debian/tmp/usr/bin/apport-cli.py:147
#: ../debian/tmp/usr/share/apport/apport-kde.py:338 ../bin/apport-cli.py:147
#: ../kde/apport-kde.py:338 ../debian/tmp/usr/share/apport/apport-gtk.py:138
msgid "(binary data)"
msgstr "(binääritiedot)"

#: ../gtk/apport-gtk.py:173 ../debian/tmp/usr/bin/apport-cli.py:175
#: ../debian/tmp/usr/share/apport/apport-kde.py:162 ../bin/apport-cli.py:175
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:282
#: ../kde/apport-kde.py:162 ../debian/tmp/usr/share/apport/apport-gtk.py:173
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:404
msgid "Send problem report to the developers?"
msgstr "Lähetetäänkö raportti ongelmasta kehittäjille?"

#: ../debian/tmp/usr/bin/apport-cli.py:176 ../bin/apport-cli.py:176
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Kun raportti ongelmasta on lähetetty, ole ystävällinen ja täytä selaimeesi\n"
"automaattisesti aukeava lomake."

#: ../debian/tmp/usr/bin/apport-cli.py:179 ../bin/apport-cli.py:179
#, python-format
msgid "&Send report (%s)"
msgstr "&Lähetä raportti (%s)"

#: ../debian/tmp/usr/bin/apport-cli.py:183 ../bin/apport-cli.py:183
msgid "&Examine locally"
msgstr "&Tutki paikallisesti"

#: ../debian/tmp/usr/bin/apport-cli.py:187 ../bin/apport-cli.py:187
msgid "&View report"
msgstr "&Tarkastele raporttia"

#: ../debian/tmp/usr/bin/apport-cli.py:188 ../bin/apport-cli.py:188
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Säilytä raporttitiedosto myöhemmin lähetettäväksi tai muualle kopioitavaksi"

#: ../debian/tmp/usr/bin/apport-cli.py:189 ../bin/apport-cli.py:189
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Peru ja &jätä jatkossa huomiotta tämän ohjelmaversion kaatumiset"

#: ../debian/tmp/usr/bin/apport-cli.py:191
#: ../debian/tmp/usr/bin/apport-cli.py:268
#: ../debian/tmp/usr/bin/apport-cli.py:300
#: ../debian/tmp/usr/bin/apport-cli.py:321 ../bin/apport-cli.py:191
#: ../bin/apport-cli.py:268 ../bin/apport-cli.py:300 ../bin/apport-cli.py:321
msgid "&Cancel"
msgstr "&Peruuta"

#: ../debian/tmp/usr/bin/apport-cli.py:219 ../bin/apport-cli.py:219
msgid "Problem report file:"
msgstr "Ongelmaraporttitiedosto:"

#: ../debian/tmp/usr/bin/apport-cli.py:225
#: ../debian/tmp/usr/bin/apport-cli.py:230 ../bin/apport-cli.py:225
#: ../bin/apport-cli.py:230
msgid "&Confirm"
msgstr "&Vahvista"

#: ../debian/tmp/usr/bin/apport-cli.py:229 ../bin/apport-cli.py:229
#, python-format
msgid "Error: %s"
msgstr "Virhe: %s"

#: ../debian/tmp/usr/bin/apport-cli.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:383 ../bin/apport-cli.py:235
#: ../kde/apport-kde.py:383
msgid "Collecting problem information"
msgstr "Kerätään tietoja ongelmasta"

#: ../debian/tmp/usr/bin/apport-cli.py:236 ../bin/apport-cli.py:236
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Kerätyt tiedot voidaan lähettää kehittäjille ohjelman parantamiseksi.\n"
"Tähän voi mennä muutama minuutti."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
#: ../debian/tmp/usr/bin/apport-cli.py:248
#: ../debian/tmp/usr/share/apport/apport-kde.py:411 ../gtk/apport-gtk.ui.h:13
#: ../bin/apport-cli.py:248 ../kde/apport-kde.py:411
msgid "Uploading problem information"
msgstr "Lähetetään tiedot ongelmasta"

#: ../debian/tmp/usr/bin/apport-cli.py:249 ../bin/apport-cli.py:249
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Kerätyt tiedot lähetetään virheseurantajärjestelmään.\n"
"Tähän voi mennä muutama minuutti."

#: ../debian/tmp/usr/bin/apport-cli.py:299 ../bin/apport-cli.py:299
msgid "&Done"
msgstr "&Valmis"

#: ../debian/tmp/usr/bin/apport-cli.py:305 ../bin/apport-cli.py:305
msgid "none"
msgstr "ei mitään"

#: ../debian/tmp/usr/bin/apport-cli.py:306 ../bin/apport-cli.py:306
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Valittu: %s. Useita valintoja:"

#: ../debian/tmp/usr/bin/apport-cli.py:322 ../bin/apport-cli.py:322
msgid "Choices:"
msgstr "Valinnat:"

#: ../debian/tmp/usr/bin/apport-cli.py:336 ../bin/apport-cli.py:336
msgid "Path to file (Enter to cancel):"
msgstr "Polku tiedostoon (Enter peruu):"

#: ../debian/tmp/usr/bin/apport-cli.py:342 ../bin/apport-cli.py:342
msgid "File does not exist."
msgstr "Tiedostoa ei ole olemassa."

#: ../debian/tmp/usr/bin/apport-cli.py:344 ../bin/apport-cli.py:344
msgid "This is a directory."
msgstr "Tämä on hakemisto."

#: ../debian/tmp/usr/bin/apport-cli.py:350 ../bin/apport-cli.py:350
msgid "To continue, you must visit the following URL:"
msgstr "Jatkaaksesi sinun tulee käydä seuraavassa URL-osoitteessa:"

#: ../debian/tmp/usr/bin/apport-cli.py:352 ../bin/apport-cli.py:352
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Voit nyt käynnistää selaimen tai kopioida tämän URL-osoitteen selaimeen "
"toisella tietokoneella."

#: ../debian/tmp/usr/bin/apport-cli.py:354 ../bin/apport-cli.py:354
msgid "Launch a browser now"
msgstr "Käynnistä selain nyt"

#: ../debian/tmp/usr/bin/apport-cli.py:368 ../bin/apport-cli.py:368
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"Ei odottavia kaatumisraportteja. Kokeile --help saadaksesi lisäinformaatiota."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:68
#: ../data/apportcheckresume.py:68
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""
"Tämä tapahtui viimeisen keskeytyksen aikana ja esti sitä jatkamasta "
"asianmukaisesti."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:70
#: ../data/apportcheckresume.py:70
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""
"Tämä tapahtui viimeisen horrostilan aikana ja esti sitä jatkamasta "
"asianmukaisesti."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:75
#: ../data/apportcheckresume.py:75
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Aloitettu ajo jumiutui erittäin lähellä loppua ja tulee ilmestymään "
"suorittuakseen loppuun normaalisti."

#: ../debian/tmp/usr/bin/apport-retrace.py:31 ../bin/apport-retrace.py:31
msgid "%prog [options] <apport problem report | crash ID>"
msgstr "%prog [valinnat] <tasaa ongelmaraportti | kaatumistunniste>"

#: ../debian/tmp/usr/bin/apport-retrace.py:33 ../bin/apport-retrace.py:33
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""
"Älä laita uusia jäljityksiä raporttiin, mutta kirjoita ne stdout:iin."

#: ../debian/tmp/usr/bin/apport-retrace.py:35 ../bin/apport-retrace.py:35
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Aloita interaktiiviinen gdb-istunto raportin ydinvedoksen kanssa (-o jättää "
"huomioimatta; ei kirjoita raporttia)"

#: ../debian/tmp/usr/bin/apport-retrace.py:37 ../bin/apport-retrace.py:37
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Kirjoita muokattu raportti annetulle tiedostolle alkuperäisen raportin "
"muuttamisen sijaan."

#: ../debian/tmp/usr/bin/apport-retrace.py:39 ../bin/apport-retrace.py:39
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Poista muistivedos raportista pinojäljityksen elvyttämisen jälkeen"

#: ../debian/tmp/usr/bin/apport-retrace.py:41 ../bin/apport-retrace.py:41
msgid "Override report's CoreFile"
msgstr "Korvaa raportin CoreFile"

#: ../debian/tmp/usr/bin/apport-retrace.py:43 ../bin/apport-retrace.py:43
msgid "Override report's ExecutablePath"
msgstr "Korvaa raportin ExecutablePath"

#: ../debian/tmp/usr/bin/apport-retrace.py:45 ../bin/apport-retrace.py:45
msgid "Override report's ProcMaps"
msgstr "Korvaa raportin ProcMaps"

#: ../debian/tmp/usr/bin/apport-retrace.py:47 ../bin/apport-retrace.py:47
msgid "Rebuild report's Package information"
msgstr "Rakenna raportin Paketti-informaatio uudelleen"

#: ../debian/tmp/usr/bin/apport-retrace.py:49 ../bin/apport-retrace.py:49
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:51 ../bin/apport-retrace.py:51
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:53 ../bin/apport-retrace.py:53
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:55 ../bin/apport-retrace.py:55
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-valgrind.py:66 ../debian/tmp/usr/bin/apport-retrace.py:59
#: ../debian/tmp/usr/bin/apport-valgrind.py:66 ../bin/apport-retrace.py:59
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:61 ../bin/apport-retrace.py:61
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Polku tiedostoon kaatumistietokannan todentamistietojen kanssa. Tätä "
"käytetään määritettäessä kaatumistunnistetta ladattaessa jäljitettyä "
"pinojälkiä. (vain jos yhtäkään seuraavista ei ole määritetty: -g, -o ja -s)"

#: ../debian/tmp/usr/bin/apport-retrace.py:63 ../bin/apport-retrace.py:63
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Näytä seuratut pinojäljet ja pyydä vahvistusta ennen niiden lähettämistä "
"kaatumistietokantaan."

#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-retrace.py:65
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Polku jäljennös-sqlite-tietokantaan (oletus: ei jälkennöksen tarkistusta)"

#: ../debian/tmp/usr/bin/apport-retrace.py:70 ../bin/apport-retrace.py:70
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""
"virheellinen lukumäärä argumentteja; käytä --help:iä saadaksesi lyhyesti apua"

#: ../debian/tmp/usr/bin/apport-retrace.py:76 ../bin/apport-retrace.py:76
msgid "You cannot use -C without -S. Stopping."
msgstr "Et voi käyttää valitsinta -C ilman valitsinta -S. Pysäytetään."

#: ../debian/tmp/usr/bin/apport-retrace.py:80 ../bin/apport-retrace.py:80
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""
"sinun tarvitsee tehdä joko paikallinen operaatio (-s, -g, -o) tai toimittaa "
"varmennustiedosto (--auth); katso --help saadaksesi lyhyesti apua"

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../debian/tmp/usr/bin/apport-retrace.py:114 ../bin/apport-retrace.py:114
msgid "OK to send these as attachments? [y/n]"
msgstr "Sopiiko näiden lähettäminen liitteinä? [y/n] (y=kyllä, n=ei)"

#: ../gtk/apport-gtk-mime.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1 ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Raportoi ongelma"

#: ../gtk/apport-gtk-mime.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2 ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Raportoi toimintahäiriöstä sovelluksen kehittäjille"

#: ../data/kernel_oops.py:28 ../debian/tmp/usr/share/apport/kernel_oops.py:28
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"Järjestelmästäsi saattaa tulla epävakaa ja se saattaa tarvita "
"uudelleenkäynnistystä."

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Katso lisätietoja man-sivulta."

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Virhe: %s ei ole suoritettava tiedosto. Lopetetaan."

#: ../gtk/apport-gtk.py:153 ../debian/tmp/usr/share/apport/apport-gtk.py:153
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Valitettavasti sovellus %s pysähtyi odottamatta."

#: ../gtk/apport-gtk.py:156 ../debian/tmp/usr/share/apport/apport-gtk.py:156
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Valitettavasti %s sulkeutui odottamatta."

#: ../gtk/apport-gtk.py:161 ../debian/tmp/usr/share/apport/apport-kde.py:176
#: ../debian/tmp/usr/share/apport/apport-kde.py:217
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:106
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:250
#: ../kde/apport-kde.py:176 ../kde/apport-kde.py:217
#: ../debian/tmp/usr/share/apport/apport-gtk.py:161
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:108
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:300
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Valitettavasti %s kohtasi sisäisen virheen."

#: ../gtk/apport-gtk.py:182 ../debian/tmp/usr/share/apport/apport-kde.py:170
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:288
#: ../kde/apport-kde.py:170 ../debian/tmp/usr/share/apport/apport-gtk.py:182
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:412
msgid "Send"
msgstr "Lähetä"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7 ../gtk/apport-gtk.py:200
#: ../gtk/apport-gtk.py:569 ../debian/tmp/usr/share/apport/apport-kde.py:271
#: ../gtk/apport-gtk.ui.h:7 ../kde/apport-kde.py:271
#: ../debian/tmp/usr/share/apport/apport-gtk.py:200
#: ../debian/tmp/usr/share/apport/apport-gtk.py:569
msgid "Show Details"
msgstr "Näytä tiedot"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10 ../gtk/apport-gtk.py:212
#: ../gtk/apport-gtk.py:280 ../gtk/apport-gtk.py:299
#: ../debian/tmp/usr/share/apport/apport-kde.py:210
#: ../debian/tmp/usr/share/apport/apport-kde.py:223 ../gtk/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:111
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:137
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:149
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:182
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:258
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:328
#: ../kde/apport-kde.py:210 ../kde/apport-kde.py:223
#: ../debian/tmp/usr/share/apport/apport-gtk.py:212
#: ../debian/tmp/usr/share/apport/apport-gtk.py:280
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:144
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:157
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:192
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:310
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:350
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:454
msgid "Continue"
msgstr "Jatka"

#: ../gtk/apport-gtk.py:224 ../debian/tmp/usr/share/apport/apport-gtk.py:224
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:276
msgid "Force Closed"
msgstr ""

#: ../gtk/apport-gtk.py:225 ../gtk/apport-gtk.py:284
#: ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-kde.py:357
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:222
#: ../kde/apport-kde.py:214 ../kde/apport-kde.py:357
#: ../debian/tmp/usr/share/apport/apport-gtk.py:225
#: ../debian/tmp/usr/share/apport/apport-gtk.py:284
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:232
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:273
msgid "Relaunch"
msgstr "Käynnistä uudelleen"

#: ../gtk/apport-gtk.py:234 ../debian/tmp/usr/share/apport/apport-gtk.py:234
#, python-format
msgid "The application %s has stopped responding."
msgstr "Sovellus \"%s\" ei vastaa."

#: ../gtk/apport-gtk.py:238 ../debian/tmp/usr/share/apport/apport-gtk.py:238
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Ohjelma \"%s\" ei vastaa."

#: ../gtk/apport-gtk.py:253 ../debian/tmp/usr/share/apport/apport-kde.py:184
#: ../kde/apport-kde.py:184 ../debian/tmp/usr/share/apport/apport-gtk.py:253
#, python-format
msgid "Package: %s"
msgstr "Paketti: %s"

#: ../gtk/apport-gtk.py:260 ../debian/tmp/usr/share/apport/apport-kde.py:190
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:132
#: ../kde/apport-kde.py:190 ../debian/tmp/usr/share/apport/apport-gtk.py:260
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:137
msgid "Sorry, a problem occurred while installing software."
msgstr "Valitettavasti ohjelmistoja asennettaessa ilmeni ongelma."

#: ../gtk/apport-gtk.py:269 ../gtk/apport-gtk.py:288
#: ../debian/tmp/usr/share/apport/apport-kde.py:197 ../kde/apport-kde.py:197
#: ../debian/tmp/usr/share/apport/apport-gtk.py:269
#: ../debian/tmp/usr/share/apport/apport-gtk.py:288
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "Sovellus %s kohtasi sisäisen virheen."

#: ../gtk/apport-gtk.py:272 ../debian/tmp/usr/share/apport/apport-kde.py:201
#: ../kde/apport-kde.py:201 ../debian/tmp/usr/share/apport/apport-gtk.py:272
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Sovellus %s sulkeutui yllättäen."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9 ../gtk/apport-gtk.py:283
#: ../debian/tmp/usr/share/apport/apport-kde.py:213 ../gtk/apport-gtk.ui.h:9
#: ../kde/apport-kde.py:213 ../debian/tmp/usr/share/apport/apport-gtk.py:283
msgid "Leave Closed"
msgstr "Sulje sovellus"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4 ../gtk/apport-gtk.py:296
#: ../debian/tmp/usr/share/apport/apport-kde.py:220 ../gtk/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:252
#: ../kde/apport-kde.py:220 ../debian/tmp/usr/share/apport/apport-gtk.py:296
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:302
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:342
msgid "If you notice further problems, try restarting the computer."
msgstr "Jos ongelmat jatkuvat, käynnistä tietokone uudelleen."

#: ../gtk/apport-gtk.py:300 ../debian/tmp/usr/share/apport/apport-kde.py:224
#: ../kde/apport-kde.py:224 ../debian/tmp/usr/share/apport/apport-gtk.py:300
msgid "Ignore future problems of this type"
msgstr "Jätä huomiotta tulevat vastaavanlaiset ongelmat"

#: ../gtk/apport-gtk.py:573 ../debian/tmp/usr/share/apport/apport-kde.py:268
#: ../kde/apport-kde.py:268 ../debian/tmp/usr/share/apport/apport-gtk.py:573
msgid "Hide Details"
msgstr "Piilota tiedot"

#: ../debian/tmp/usr/share/apport/apport-kde.py:294 ../kde/apport-kde.py:294
msgid "Username:"
msgstr "Käyttäjätunnus"

#: ../debian/tmp/usr/share/apport/apport-kde.py:295 ../kde/apport-kde.py:295
msgid "Password:"
msgstr "Salasana:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:382 ../kde/apport-kde.py:382
msgid "Collecting Problem Information"
msgstr "Kerätään tietoja ongelmasta"

#: ../debian/tmp/usr/share/apport/apport-kde.py:384 ../kde/apport-kde.py:384
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Kerätty tieto voidaan lähettää kehittäjille ohjelmiston parantamiseksi. Tämä "
"voi kestää muutamia minuutteja."

#: ../debian/tmp/usr/share/apport/apport-kde.py:410 ../kde/apport-kde.py:410
msgid "Uploading Problem Information"
msgstr "Lähetetään tiedot ongelmasta"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
#: ../debian/tmp/usr/share/apport/apport-kde.py:412 ../gtk/apport-gtk.ui.h:15
#: ../kde/apport-kde.py:412
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Kerättyjä tietoja lähetetään vianseurantajärjestelmään. Tämä saattaa kestää "
"muutamia minuutteja."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-kde.py:446
#: ../debian/tmp/usr/share/apport/apport-kde.py:482 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:446 ../kde/apport-kde.py:482
msgid "Apport"
msgstr "Apport"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Kerää järjestelmätiedot"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Vikailmoitukseen tarvittavien järjestelmätietojen kerääminen vaatii "
"tunnistautumisen"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Järjestelmän ongelmaraportit"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr "Anna salasanasi nähdäksesi järjestelmäohjelmien ongelmaraportteja"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Crash report"
msgstr "Ohjelmisto lopetti toimintansa"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Valitettavasti havaittiin sisäinen virhe.</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr "Auta kehittäjiä korjaamaan tämä ongelma lähettämällä vikailmoitus"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6 ../gtk/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr "Älä huomioi tämän ohjelmiston kaatumisia jatkossa"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr "_Tutki paikallisesti"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11 ../gtk/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Kerätään tietoja ongelmasta</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../gtk/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr "Kerätään tietoja ongelman korjaamisen helpottamiseksi."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14 ../gtk/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Lähetetään tietoja ongelmasta</b></big>"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport-kaatumistiedosto"

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Käyttö: %s <raportti> <kohdehakemisto>"

#: ../debian/tmp/usr/bin/apport-unpack.py:46 ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr "Kohdehakemisto on jo olemassa, eikä ole tyhjä."

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "Voit auttaa kehittäjiä korjaaman ongelman ilmoittamalla siitä."

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "Paketin \"%s\" asennus tai päivitys epäonnistui."

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Täydellinen raportti (suositus; %s)"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Lähetetäänkö ongelmaraportti sovelluksen kehittäjille?</b></big>\n"
#~ "\n"
#~ "Ole hyvä ja täytä automaattisesti selaimeen auennut lomake, kun "
#~ "ongelmaraportti on lähetetty."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "Jos et tehnyt mitään luottamuksellista (syöttänyt salasanoja tai muita "
#~ "henkilökohtaisia tietoja), voit auttaa kehittämään ohjelmaa raportoimalla "
#~ "ongelmasta."

#, python-format
#~ msgid "Sorry, %s closed unexpectedly"
#~ msgstr "Ikävä kyllä %s sulkeutui yllättäen"

#~ msgid "Application problem"
#~ msgstr "Ongelma sovelluksessa"

#~ msgid "&Details..."
#~ msgstr "&Yksityiskohdat..."

#~ msgid "_Send Report"
#~ msgstr "_Lähetä raportti"

#~ msgid "Generic error"
#~ msgstr "Yleinen virhe"

#~ msgid ""
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "Kun raportti on lähetetty, ole hyvä ja täytä selaimeesi automaattisesti "
#~ "aukeava lomake."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Jos et ollut tekemässä mitään luottamuksellista (kuten syöttänyt salasanoja "
#~ "tai muuta\n"
#~ "henkilökohtaista tietoa), voit auttaa ohjelman kehittämisessä raportoimalla\n"
#~ "ongelman."

#~ msgid "Restart _Program"
#~ msgstr "Uudelleenkäynnistä _ohjelma"

#, python-format
#~ msgid "Sorry, the package \"%s\" failed to install or upgrade."
#~ msgstr "Ikävä kyllä paketin \"%s\" asennus tai päivitys epäonnistui."

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">Paketin \"%s\" asennus tai päivitys "
#~ "epäonnistui.</span>"

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Lähetä täydellinen raportti (suositeltavaa; %s)"

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Pelkistetty raportti (hidas Internet-yhteys; %s)"

#, python-format
#~ msgid "Sorry, %s closed unexpectedly."
#~ msgstr "Ikävä kyllä %s sulkeutui yllättäen."

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Jätä tämän ohjelmaversion kaatumiset huomiotta jatkossa"

#~ msgid "Restart &Program"
#~ msgstr "Käynnistä &ohjelma uudelleen"

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Lähetä &suppea raportti (hitaille Internet-yhteyksille; %s)"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "Tämä poistaa joitain isoimpia osuuksia raportista. Osuudet ovat hyödyllisiä "
#~ "ohjelman kehittäjille ongelman selvittämisessä mutta et välttämättä halua "
#~ "odottaa niiden lähettämistä, jos Internet-yhteytesi on hidas."

#~ msgid "&Report Problem..."
#~ msgstr "&Raportoi ongelma..."

#~ msgid "_Report Problem..."
#~ msgstr "_Raportoi ongelma..."

#~ msgid "&Send"
#~ msgstr "&Lähetä"

#~ msgid "Kernel problem"
#~ msgstr "Ongelma käyttöjärjestelmän ytimessä"

#~ msgid "&Ignore future crashes of this program version"
#~ msgstr "Älä huomioi tämän ohjelmaversion kaatumisia jatkossa"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr "Voi auttaa kehittäjiä korjaamaan ongelman raportoimalla ongelmasta."

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "Tämä ei ole alkuperäinen %s-paketti"

#, python-format
#~ msgid "Sorry, the program \"%s\" closed unexpectedly."
#~ msgstr "Ikävä kyllä ohjelma \"%s\" sulkeutui yllättäen."

#~ msgid "Content of the report"
#~ msgstr "Raportin sisältö"

#~ msgid "Package problem"
#~ msgstr "Ongelma paketissa"

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "Järjestelmässä tapahtui vakava ydinongelma."

#~ msgid "Send this data to the developers?"
#~ msgstr "Lähetetäänkö nämä tiedot kehittäjille?"

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s sulkeutui yllättäen %s %s."

#, python-format
#~ msgid "Sorry, the application %s has closed unexpectedly."
#~ msgstr "Valitettavasti sovellus %s sulkeutui odottamatta."
