# Finnish translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-05-17 09:15-0700\n"
"PO-Revision-Date: 2015-04-27 21:47+0000\n"
"Last-Translator: Timo Jyrinki <Unknown>\n"
"Language-Team: Finnish <fi@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2021-04-08 06:53+0000\n"
"X-Generator: Launchpad (build 57f1f603f707b9cfa764cae8dd0f3999026b4763)\n"
"Language: fi\n"

#: ../kde/apport-kde-mime.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Raportoi ongelma..."

#: ../kde/apport-kde-mime.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Raportoi toimintahäiriöstä sovelluksen kehittäjille"

#: ../kde/apport-kde.py:363 ../gtk/apport-gtk.py:146
#: ../debian/tmp/usr/share/apport/apport-gtk.py:146 ../bin/apport-cli.py:166
#: ../debian/tmp/usr/share/apport/apport-kde.py:363
#: ../debian/tmp/usr/bin/apport-cli.py:166
msgid "(binary data)"
msgstr "(binääritiedot)"

#: ../gtk/apport-gtk.py:161 ../debian/tmp/usr/share/apport/apport-gtk.py:161
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Valitettavasti sovellus %s pysähtyi odottamatta."

#: ../gtk/apport-gtk.py:164 ../debian/tmp/usr/share/apport/apport-gtk.py:164
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Valitettavasti %s sulkeutui odottamatta."

#: ../kde/apport-kde.py:200 ../kde/apport-kde.py:238 ../gtk/apport-gtk.py:169
#: ../debian/tmp/usr/share/apport/apport-gtk.py:169
#: ../debian/tmp/usr/share/apport/apport-kde.py:200
#: ../debian/tmp/usr/share/apport/apport-kde.py:238
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Valitettavasti %s kohtasi sisäisen virheen."

#: ../kde/apport-kde.py:186 ../gtk/apport-gtk.py:181
#: ../debian/tmp/usr/share/apport/apport-gtk.py:181 ../bin/apport-cli.py:194
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
#: ../debian/tmp/usr/share/apport/apport-kde.py:186 ../gtk/apport-gtk.ui.h:6
#: ../debian/tmp/usr/bin/apport-cli.py:194
msgid "Send problem report to the developers?"
msgstr "Lähetetäänkö raportti ongelmasta kehittäjille?"

#: ../kde/apport-kde.py:194 ../gtk/apport-gtk.py:188
#: ../debian/tmp/usr/share/apport/apport-gtk.py:188
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
#: ../debian/tmp/usr/share/apport/apport-kde.py:194 ../gtk/apport-gtk.ui.h:14
msgid "Send"
msgstr "Lähetä"

#: ../kde/apport-kde.py:292 ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:575
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:575
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-kde.py:292 ../gtk/apport-gtk.ui.h:11
msgid "Show Details"
msgstr "Näytä tiedot"

#: ../kde/apport-kde.py:231 ../kde/apport-kde.py:244 ../gtk/apport-gtk.py:216
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216
#: ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-kde.py:244
msgid "Continue"
msgstr "Jatka"

#: ../gtk/apport-gtk.py:239 ../debian/tmp/usr/share/apport/apport-gtk.py:239
#, python-format
msgid "The application %s has stopped responding."
msgstr "Sovellus \"%s\" ei vastaa."

#: ../gtk/apport-gtk.py:243 ../debian/tmp/usr/share/apport/apport-gtk.py:243
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Ohjelma \"%s\" ei vastaa."

#: ../kde/apport-kde.py:208 ../gtk/apport-gtk.py:259
#: ../debian/tmp/usr/share/apport/apport-gtk.py:259
#: ../debian/tmp/usr/share/apport/apport-kde.py:208
#, python-format
msgid "Package: %s"
msgstr "Paketti: %s"

#: ../kde/apport-kde.py:214 ../gtk/apport-gtk.py:265
#: ../debian/tmp/usr/share/apport/apport-gtk.py:265
#: ../debian/tmp/usr/share/apport/apport-kde.py:214
msgid "Sorry, a problem occurred while installing software."
msgstr "Valitettavasti ohjelmistoja asennettaessa ilmeni ongelma."

#: ../kde/apport-kde.py:220 ../gtk/apport-gtk.py:274 ../gtk/apport-gtk.py:289
#: ../debian/tmp/usr/share/apport/apport-gtk.py:274
#: ../debian/tmp/usr/share/apport/apport-gtk.py:289
#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "Sovellus %s kohtasi sisäisen virheen."

#: ../kde/apport-kde.py:223 ../gtk/apport-gtk.py:277
#: ../debian/tmp/usr/share/apport/apport-gtk.py:277
#: ../debian/tmp/usr/share/apport/apport-kde.py:223
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Sovellus %s sulkeutui yllättäen."

#: ../kde/apport-kde.py:241 ../gtk/apport-gtk.py:297
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-kde.py:241 ../gtk/apport-gtk.ui.h:7
msgid "If you notice further problems, try restarting the computer."
msgstr "Jos ongelmat jatkuvat, käynnistä tietokone uudelleen."

#: ../kde/apport-kde.py:245 ../gtk/apport-gtk.py:299
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299
#: ../debian/tmp/usr/share/apport/apport-kde.py:245
msgid "Ignore future problems of this type"
msgstr "Jätä huomiotta tulevat vastaavanlaiset ongelmat"

#: ../kde/apport-kde.py:289 ../gtk/apport-gtk.py:579
#: ../debian/tmp/usr/share/apport/apport-gtk.py:579
#: ../debian/tmp/usr/share/apport/apport-kde.py:289
msgid "Hide Details"
msgstr "Piilota tiedot"

#: ../debian/tmp/usr/bin/apport-retrace.py:34 ../bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""
"Älä laita uusia jäljityksiä raporttiin, mutta kirjoita ne stdout:iin."

#: ../debian/tmp/usr/bin/apport-retrace.py:36 ../bin/apport-retrace.py:36
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Aloita interaktiiviinen gdb-istunto raportin ydinvedoksen kanssa (-o jättää "
"huomioimatta; ei kirjoita raporttia)"

#: ../debian/tmp/usr/bin/apport-retrace.py:38 ../bin/apport-retrace.py:38
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Kirjoita muokattu raportti annetulle tiedostolle alkuperäisen raportin "
"muuttamisen sijaan"

#: ../debian/tmp/usr/bin/apport-retrace.py:41 ../bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Poista muistivedos raportista pinojäljityksen elvyttämisen jälkeen"

#: ../debian/tmp/usr/bin/apport-retrace.py:43 ../bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr "Korvaa raportin CoreFile"

#: ../debian/tmp/usr/bin/apport-retrace.py:45 ../bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr "Korvaa raportin ExecutablePath"

#: ../debian/tmp/usr/bin/apport-retrace.py:47 ../bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr "Korvaa raportin ProcMaps"

#: ../debian/tmp/usr/bin/apport-retrace.py:49 ../bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr "Rakenna raportin Paketti-informaatio uudelleen"

#: ../debian/tmp/usr/bin/apport-retrace.py:51 ../bin/apport-retrace.py:51
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Rakenna väliaikainen hiekkalaatikko ja lataa/asenna tarvittavat paketit ja "
"virheenkorjauksen symbolit sinne; ilman tätä valintaa se olettaa "
"tarvittavien pakettien ja virheenkorjauksen symbolien olevan asennettuna "
"järjestelmään. Argumentti osoittaa paketointijärjestelmän asetusten "
"perushakemistoon; jos määrittelet \"system\", se tulee käyttämään "
"järjestelmän asetustiedostoja, mutta voi silloin ainoastaan jäljittää "
"kaatumisia, jotka tapahtuivat tällä hetkellä ajettavassa julkaisuversiossa."

#: ../debian/tmp/usr/bin/apport-retrace.py:53 ../bin/apport-retrace.py:53
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""
"Rakenna toinen väliaikainen hiekkalaatikko gdb:n ja sen riippuvuuksien "
"asentamista varten käyttäen samaa julkaisuversiota kuin raportissa, "
"mieluummin kuin mitä tahansa versiota gdb:stä joka sinulla on asennettuna."

#: ../debian/tmp/usr/bin/apport-retrace.py:55 ../bin/apport-retrace.py:55
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""
"Raportoi latauksen/asentamisen eteneminen asennettaessa paketteja "
"hiekkalaatikkoon"

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid "Prepend timestamps to log messages, for batch operation"
msgstr "Liitä aikaleimat lokitiedostojen alkuun, eräoperaatiota varten"

#: ../debian/tmp/usr/bin/apport-retrace.py:59 ../bin/apport-retrace.py:59
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"Luo ja käytä kolmannen osapuolen pakettivarastoja raporteissa määritellyistä "
"lähteistä"

#: ../debian/tmp/usr/bin/apport-retrace.py:61 ../bin/apport-retrace.py:61
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Välimuistin hakemisto hiekkalaatikkoon ladattaville paketeille"

#: ../debian/tmp/usr/bin/apport-retrace.py:63 ../bin/apport-retrace.py:63
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Hakemisto purettaville paketeille. Tulevat suorituskerrat olettavat jokaisen "
"jo ladatun paketin tulevan puretuksi tähän hiekkalaatikkoon."

#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-retrace.py:65
#: ../debian/tmp/usr/bin/apport-valgrind.py:66 ../bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr "Lataa ekstrapakkaukset hiekkalaatikkoon (voi kestää pitkään)"

#: ../debian/tmp/usr/bin/apport-retrace.py:67 ../bin/apport-retrace.py:67
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Polku tiedostoon kaatumistietokannan todentamistietojen kanssa. Tätä "
"käytetään määritettäessä kaatumistunnistetta ladattaessa jäljitettyä "
"pinojälkiä. (vain jos yhtäkään seuraavista ei ole määritetty: -g, -o ja -s)"

#: ../debian/tmp/usr/bin/apport-retrace.py:69 ../bin/apport-retrace.py:69
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Näytä seuratut pinojäljet ja pyydä vahvistusta ennen niiden lähettämistä "
"kaatumistietokantaan."

#: ../debian/tmp/usr/bin/apport-retrace.py:71 ../bin/apport-retrace.py:71
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Polku jäljennös-sqlite-tietokantaan (oletus: ei jälkennöksen tarkistusta)"

#: ../debian/tmp/usr/bin/apport-retrace.py:73 ../bin/apport-retrace.py:73
msgid "Do not add StacktraceSource to the report."
msgstr "Älä lisää pinolistauslähteitä raporttiin."

#: ../debian/tmp/usr/bin/apport-retrace.py:82 ../bin/apport-retrace.py:82
msgid "You cannot use -C without -S. Stopping."
msgstr "Et voi käyttää valitsinta -C ilman valitsinta -S. Pysäytetään."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../debian/tmp/usr/bin/apport-retrace.py:115 ../bin/apport-retrace.py:115
msgid "OK to send these as attachments? [y/n]"
msgstr "Sopiiko näiden lähettäminen liitteinä? [y/n] (y=kyllä, n=ei)"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport-kaatumistiedosto"

#: ../debian/tmp/usr/bin/apport-valgrind.py:37 ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Katso lisätietoja man-sivulta."

#: ../debian/tmp/usr/bin/apport-valgrind.py:43 ../bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr "syötä valgrindin tuottaman lokitiedoston nimi"

#: ../debian/tmp/usr/bin/apport-valgrind.py:46 ../bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"käytä uudelleen jo aikaisemmin luotua hiekkalaatikkokansiota (SDIR), tai jos "
"sitä ei ole, luo sellainen"

#: ../debian/tmp/usr/bin/apport-valgrind.py:50 ../bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"älä luo tai käytä uudelleen hiekkalaatikkokansiota ylimääräisiä "
"virheenkorjaussymboleja varten, vaan luota vain asennettuihin "
"virheenkorjaussymboleihin."

#: ../debian/tmp/usr/bin/apport-valgrind.py:54 ../bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"uudelleenkäytä aiemmin luotua välimuistin hakemistoa  (CDIR) tai, jos sitä "
"ei ole, luo se"

#: ../debian/tmp/usr/bin/apport-valgrind.py:58 ../bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""
"raportoi latauksen/asennuksen eteneminen  asennettaessa paketteja "
"hiekkalaatikkoon"

#: ../debian/tmp/usr/bin/apport-valgrind.py:62 ../bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""
"suoritettava, joka suoritetaan valgrind:n muistin tarkastustyökalulla "
"muistivuotojen havaitsemiseksi"

#: ../debian/tmp/usr/bin/apport-valgrind.py:97 ../bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Virhe: %s ei ole suoritettava tiedosto. Lopetetaan."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:139
#: ../apport/ui.py:139
msgid "This package does not seem to be installed correctly"
msgstr "Tätä pakettia ei ole asennettu oikein"

#: ../apport/ui.py:130
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:130
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"Tämä ei ole virallinen %s-paketti. Poista kolmansien osapuolten paketit ja "
"yritä sitten uudelleen."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:166
#: ../apport/ui.py:166
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Järjestelmässä on asennettuna joidenkin pakettien vanhentuneita versiota. "
"Päivitä seuraavat paketit ja tarkista, uusiutuuko ongelma:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:303
#: ../apport/ui.py:303
msgid "unknown program"
msgstr "tuntematon sovellus"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:304
#: ../apport/ui.py:304
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Ikävä kyllä ohjelma \"%s\" sulkeutui yllättäen"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:306
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1458
#: ../apport/ui.py:306 ../apport/ui.py:1458
#, python-format
msgid "Problem in %s"
msgstr "Ongelma osan %s kanssa"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:307
#: ../apport/ui.py:307
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Muistia ei ole vapaana tarpeeksi ongelman automaattiseen analysointiin ja "
"virheraportin lähettämiseen."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:362
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:370
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:519
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:522
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:727
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1264
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1430
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1434
#: ../apport/ui.py:362 ../apport/ui.py:370 ../apport/ui.py:519
#: ../apport/ui.py:522 ../apport/ui.py:727 ../apport/ui.py:1264
#: ../apport/ui.py:1430 ../apport/ui.py:1434
msgid "Invalid problem report"
msgstr "Virheellinen ongelmaraportti"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:363
#: ../apport/ui.py:363
msgid "You are not allowed to access this problem report."
msgstr "Sinulla ei ole lukuoikeuksia tähän ongelmaraporttiin."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:366
#: ../apport/ui.py:366
msgid "Error"
msgstr "Virhe"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:367
#: ../apport/ui.py:367
msgid "There is not enough disk space available to process this report."
msgstr "Levyllä ei ole tarpeeksi tilaa raportin käsittelyyn."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:411
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:500
#: ../apport/ui.py:411 ../apport/ui.py:500
msgid "Invalid PID"
msgstr "PID-numero ei kelpaa"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:412
#: ../apport/ui.py:412
msgid "The specified process ID does not exist."
msgstr "Määriteltyä prosessitunnistetta ei ole."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:415
#: ../apport/ui.py:415
msgid "Not your PID"
msgstr "Ei sinun PID"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:416
#: ../apport/ui.py:416
msgid "The specified process ID does not belong to you."
msgstr "Määritelty prosessitunniste ei kuulu sinulle."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:467
#: ../apport/ui.py:467
msgid "No package specified"
msgstr "Pakettia ei ole määritelty"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:468
#: ../apport/ui.py:468
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Paketti tai PID-tunniste on annettava. Katso lisätietoja käyttämällä "
"valitsinta --help."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:497
#: ../apport/ui.py:497
msgid "Permission denied"
msgstr "Lupa evätty"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:498
#: ../apport/ui.py:498
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Kyseinen prosessi ei kuulu sinulle. Aja tämä ohjelma prosessin omistajana "
"tai pääkäyttäjänä."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:501
#: ../apport/ui.py:501
msgid "The specified process ID does not belong to a program."
msgstr "Määritetty prosessin ID-numero ei kuulu kyseiselle ohjelmalle."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:520
#: ../apport/ui.py:520
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Oirekomentosarja %s ei määritellyt vaikuttanutta pakettia"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:523
#: ../apport/ui.py:523
#, python-format
msgid "Package %s does not exist"
msgstr "Pakettia %s ei ole olemassa"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:739
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:744
#: ../apport/ui.py:552 ../apport/ui.py:739 ../apport/ui.py:744
msgid "Cannot create report"
msgstr "Raporttia ei voida luoda"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:567
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:613
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:629
#: ../apport/ui.py:567 ../apport/ui.py:613 ../apport/ui.py:629
msgid "Updating problem report"
msgstr "Päivitetään ongelmaraporttia"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:568
#: ../apport/ui.py:568
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Et ole tämän ongelman raportoija tai ilmoittanut ongelmasta aikaisemmin; "
"ilmoitus on mahdollisesti kaksoiskopio tai se on jo suljettu aikaisemmin.\n"
"\n"
"Ole hyvä, ja luo uusi raportti käyttäen \"apport-bug\" määrittelyä."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:577
#: ../apport/ui.py:577
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Et ole tämän ongelman raportoija. On helpompaa merkitä ongelma jonkin toisen "
"samankaltaisen ongelman kopioksi, kuin siirtää kommenttisi ja liitteesi "
"täysin uuteen ongelmaraporttiin.\n"
"\n"
"Suosittelemme että lähetät uuden ongelmaraportin käyttäen \"apport-bug\" "
"määrittelyä ja lisäät tähän ongelmaan kommentin lisäämästäsi uudesta "
"ilmoituksesta.\n"
"\n"
"Haluatko todella jatkaa?"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:614
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:630
#: ../apport/ui.py:614 ../apport/ui.py:630
msgid "No additional information collected."
msgstr "Lisätietoja ei kerätty."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:681
#: ../apport/ui.py:681
msgid "What kind of problem do you want to report?"
msgstr "Millainen ongelma raportoidaan?"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:698
#: ../apport/ui.py:698
msgid "Unknown symptom"
msgstr "Tuntematon ongelma"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:699
#: ../apport/ui.py:699
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Ongelmaa \"%s\" ei tunnistettu."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:730
#: ../apport/ui.py:730
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Kun olet sulkenut tämän viestin napsauta sen sovelluksen ikkunaa, johon "
"liittyvän virheraportin haluat tehdä."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:740
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:745
#: ../apport/ui.py:740 ../apport/ui.py:745
msgid "xprop failed to determine process ID of the window"
msgstr "xprop ei onnistunut selvittämään ikkunaan ID-tunnistenumeroa"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:759
#: ../apport/ui.py:759
msgid "%prog <report number>"
msgstr "%prog <raportin numero>"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:761
#: ../apport/ui.py:761
msgid "Specify package name."
msgstr "Määritä paketin nimi."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:763
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:815
#: ../apport/ui.py:763 ../apport/ui.py:815
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""
"Lisää raporttiin liittyvä tunniste. Tämä voidaan tehdä useampia kertoja."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:794
#: ../apport/ui.py:794
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [valinnat] [ongelma|pid|paketti|ohjelman "
"polku|.apport/.kaatumisraportti]"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:797
#: ../apport/ui.py:797
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Aloita ohjelmavirheiden kirjaustilassa. Se vaatii --package ja valinnaisen --"
"pid:n, tai vain --pid:n. Jos kumpaakaan ei anneta, näytä lista tunnetuista "
"oireista. (Epäsuora jos yksi argumentti on annettu.)"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:799
#: ../apport/ui.py:799
msgid "Click a window as a target for filing a problem report."
msgstr "Napsauta ikkunaa, johon liittyvän virheraportin haluat tehdä."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:801
#: ../apport/ui.py:801
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"Aloita ohjelmavirheiden päivitystilassa. Voi ottaa valinnaisen valitsimen --"
"package."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:803
#: ../apport/ui.py:803
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Arkistoi ohjelmavirheen raportti oireena. (Epäsuorasti jos oireen nimi on "
"annettu vain argumenttina.)"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:805
#: ../apport/ui.py:805
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Määritä paketin nimi --file-bug-tilassa. Tämä on valinnainen jos --pid on "
"määritetty. (Epäsuorasti jos paketin nimi on annettu vain argumenttina.)"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:807
#: ../apport/ui.py:807
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"Määritä suoritettava ohjelma --file-bug–tilassa. Jos tämä on määritetty, "
"virheraportti sisältää enemmän tietoa.  (Epäsuorasti, jos pid on annettu "
"ainoana argumenttina.)"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:809
#: ../apport/ui.py:809
msgid "The provided pid is a hanging application."
msgstr "Annettu pid on ohjelma, joka ei vastaa."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:811
#: ../apport/ui.py:811
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Raportoi kaatuminen annetusta .apport tai .crash-tiedostosta odottavien "
"sijaan kohdassa %s. (Epäsuora jos tiedosta on annettu vain argumenttina.)"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:813
#: ../apport/ui.py:813
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"Virheiden arkistointitilassa, tallenna kerätyt tiedot tiedostoon niiden "
"raportoimisen sijaan. Tämä tiedosto voidaan raportoida myöhemmin toiselta "
"koneelta."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:817
#: ../apport/ui.py:817
msgid "Print the Apport version number."
msgstr "Tulosta Apport-versionumero."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:968
#: ../apport/ui.py:968
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"Tämä käynnistää apport-retracen pääteikkunnassa ongelman tutkimiseksi."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:969
#: ../apport/ui.py:969
msgid "Run gdb session"
msgstr "Käynnistä gdb sessiossa"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:970
#: ../apport/ui.py:970
msgid "Run gdb session without downloading debug symbols"
msgstr "Suorita gdb-istunto ilman virheenjäljityssymbolien lataamista"

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:972
#: ../apport/ui.py:972
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Päivitä %s täysin symbolisella pinolistauksella"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1008
#: ../apport/ui.py:1008
msgid "Can't remember send report status settings"
msgstr "Ei muisteta raportin lähetystilan asetuksia"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1009
#: ../apport/ui.py:1009
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""
"Kaatumisilmoitusraportin tilan tallennus epäonnistui. Ei voida asettaa "
"automaattista tai ei ikinä raportointitiloja."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1068
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1078
#: ../apport/ui.py:1068 ../apport/ui.py:1078
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""
"Tämä ongelmaraportti kytkeytyy ohjelmaan, joka ei ole enää asennettu."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1093
#: ../apport/ui.py:1093
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr "Ongelma koskee ohjelmaa %s, joka on muuttunut kaatumisen jälkeen."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1140
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1221
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1436
#: ../apport/ui.py:1140 ../apport/ui.py:1221 ../apport/ui.py:1436
msgid "This problem report is damaged and cannot be processed."
msgstr "Tämä ongelman raportti on vahingoittunut, eikä sitä voida käsitellä."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1130
#: ../apport/ui.py:1130
#, python-format
msgid ""
"This report is about a snap published by %s. Contact them via %s for help."
msgstr ""
"Tämä raportti koskee snap-pakettia, jonka on julkaissut %s. Ohjeita saat "
"olemalla yhteydessä julkaisijaan: %s."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1133
#: ../apport/ui.py:1133
#, python-format
msgid ""
"This report is about a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""
"Tämä raportti koskee snap-pakettia, jonka on julkaissut %s. Yhteydenotto-"
"osoitetta ei ole määritetty; käy keskustelupalstalla "
"https://forum.snapcraft.io/ saadaksesi ohjeita."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1145
#: ../apport/ui.py:1145
msgid "This report is about a package that is not installed."
msgstr "Tämä raportti koskee pakettia, jota ei ole asennettu."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1149
#: ../apport/ui.py:1149
msgid "An error occurred while attempting to process this problem report:"
msgstr "Virhe käsiteltäessä ongelmaraporttia:"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1148
#: ../apport/ui.py:1148
#, python-format
msgid ""
"You are about to report a bug against the deb package, but you also a have "
"snap published by %s installed. You can contact them via %s for help. Do you "
"want to continue with the bug report against the deb?"
msgstr ""
"Olet lähettämässä deb–pakettia koskevaa virheraporttia, mutta sinulla on "
"myös asennettuna %s julkaisema snap–paketti. Voit ottaa heihin yhteyttä "
"käyttäen %s apuna. Haluatko jatkaa deb–pakettia koskevan virheraportin "
"lähettämistä?"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1150
#: ../apport/ui.py:1150
#, python-format
msgid ""
"You are about to report a bug against the deb package, but you also a have "
"snap published by %s installed. For the snap, no contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help. Do you "
"want to continue with the bug report against the deb?"
msgstr ""
"Olet lähettämässä deb–pakettia koskevaa virheraporttia, mutta sinulla on "
"myös asennettuna %s julkaisema snap–paketti. Yhteystietoja ei ole tarjottu "
"snap–paketille; vieraile foorumilla osoitteessa https://forum.snapcraft.io/ "
"saadaksesi apua. Haluatko jatkaa deb–pakettia koskevan virheraportin "
"lähettämistä?"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1265
#: ../apport/ui.py:1265
msgid "Could not determine the package or source package name."
msgstr "Paketin tai lähdekoodipaketin nimeä ei voi määrittää."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1283
#: ../apport/ui.py:1283
msgid "Unable to start web browser"
msgstr "Selaimen käynnistäminen epäonnistui"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1284
#: ../apport/ui.py:1284
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Verkkoselainta ei saatu käynnistettyä avattaessa sivua %s."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1384
#: ../apport/ui.py:1384
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "Ole hyvä ja syötä %s bugi raportointi järjestelmän kirjautumistiedot"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1396
#: ../apport/ui.py:1396
msgid "Network problem"
msgstr "Verkko-ongelma"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1398
#: ../apport/ui.py:1398
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Kaatumistietokantaan ei voi yhdistää. Tarkista Internet-yhteyden toimivuus."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1425
#: ../apport/ui.py:1425
msgid "Memory exhaustion"
msgstr "Muisti ei riitä"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1426
#: ../apport/ui.py:1426
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Järjestelmässäsi ei ole tarpeeksi muistia tämän kaatumisraportin käsittelyyn."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1461
#: ../apport/ui.py:1461
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Ongelman raportoiminen ei onnistunut:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1517
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1524
#: ../apport/ui.py:1517 ../apport/ui.py:1524
msgid "Problem already known"
msgstr "Ongelma on jo tiedossa"

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1518
#: ../apport/ui.py:1518
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Tämä ongelma raportoitiin jo virheraportissa, joka on näkyvissä selaimessa. "
"Tarkista, voisitko lisätä joitakin kehittäjiä auttavaa tietoa."

#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1525
#: ../apport/ui.py:1525
msgid "This problem was already reported to developers. Thank you!"
msgstr ""
"Tästä ongelmasta on jo ilmoitettu kehittäjille. Kiitos kuitenkin "
"auttamishalustasi!"

#: ../kde/apport-kde.py:469 ../kde/apport-kde.py:504 ../kde/apport-kde.py:524
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-kde.py:469
#: ../debian/tmp/usr/share/apport/apport-kde.py:504
#: ../debian/tmp/usr/share/apport/apport-kde.py:524 ../gtk/apport-gtk.ui.h:1
msgid "Apport"
msgstr "Apport"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Peru"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "OK"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4 ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Ohjelmisto lopetti toimintansa"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Valitettavasti havaittiin sisäinen virhe.</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr "Muista tämä myöhemmin"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9 ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Älä huomioi tämän ohjelmiston kaatumisia jatkossa"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10 ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr "Käynnistä sovellus uudelleen"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "_Tutki paikallisesti"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr "Älä lähetä"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Kerätään tietoja ongelmasta</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16 ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr "Kerätään tietoja ongelman korjaamisen helpottamiseksi."

#: ../kde/apport-kde.py:435 ../bin/apport-cli.py:267
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
#: ../debian/tmp/usr/share/apport/apport-kde.py:435 ../gtk/apport-gtk.ui.h:17
#: ../debian/tmp/usr/bin/apport-cli.py:267
msgid "Uploading problem information"
msgstr "Lähetetään tiedot ongelmasta"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18 ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Lähetetään tietoja ongelmasta</b></big>"

#: ../kde/apport-kde.py:436 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19
#: ../debian/tmp/usr/share/apport/apport-kde.py:436 ../gtk/apport-gtk.ui.h:19
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Kerättyjä tietoja lähetetään vianseurantajärjestelmään. Tämä saattaa kestää "
"muutamia minuutteja."

#: ../debian/tmp/usr/share/apport/kernel_oops.py:29 ../data/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"Järjestelmästäsi saattaa tulla epävakaa ja se saattaa tarvita "
"uudelleenkäynnistystä."

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Käyttö: %s <raportti> <kohdehakemisto>"

#: ../debian/tmp/usr/bin/apport-unpack.py:42 ../bin/apport-unpack.py:42
msgid "Destination directory exists and is not empty."
msgstr "Kohdehakemisto on jo olemassa, eikä ole tyhjä."

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Kerää järjestelmätiedot"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Vikailmoitukseen tarvittavien järjestelmätietojen kerääminen vaatii "
"tunnistautumisen"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Järjestelmän ongelmaraportit"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr "Anna salasanasi nähdäksesi järjestelmäohjelmien ongelmaraportteja"

#: ../bin/apport-cli.py:80 ../debian/tmp/usr/bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr "Paina mitä tahansa näppäintä jatkaaksesi..."

#: ../bin/apport-cli.py:87 ../debian/tmp/usr/bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr "Kuinka haluat edetä? Vaihtoehdot ovat:"

#: ../bin/apport-cli.py:100 ../debian/tmp/usr/bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr "Ole hyvä ja valitse (%s):"

#: ../bin/apport-cli.py:164 ../debian/tmp/usr/bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr "(%i tavua)"

#: ../bin/apport-cli.py:195 ../debian/tmp/usr/bin/apport-cli.py:195
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Kun raportti ongelmasta on lähetetty, ole ystävällinen ja täytä selaimeesi\n"
"automaattisesti aukeava lomake."

#: ../bin/apport-cli.py:198 ../debian/tmp/usr/bin/apport-cli.py:198
#, python-format
msgid "&Send report (%s)"
msgstr "&Lähetä raportti (%s)"

#: ../bin/apport-cli.py:202 ../debian/tmp/usr/bin/apport-cli.py:202
msgid "&Examine locally"
msgstr "&Tutki paikallisesti"

#: ../bin/apport-cli.py:206 ../debian/tmp/usr/bin/apport-cli.py:206
msgid "&View report"
msgstr "Tarkastele &raporttia"

#: ../bin/apport-cli.py:207 ../debian/tmp/usr/bin/apport-cli.py:207
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Säilytä raporttitiedosto myöhemmin lähetettäväksi tai muualle kopioitavaksi"

#: ../bin/apport-cli.py:208 ../debian/tmp/usr/bin/apport-cli.py:208
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Peru ja &jätä jatkossa huomiotta tämän ohjelmaversion kaatumiset"

#: ../bin/apport-cli.py:210 ../bin/apport-cli.py:287 ../bin/apport-cli.py:319
#: ../bin/apport-cli.py:340 ../debian/tmp/usr/bin/apport-cli.py:210
#: ../debian/tmp/usr/bin/apport-cli.py:287
#: ../debian/tmp/usr/bin/apport-cli.py:319
#: ../debian/tmp/usr/bin/apport-cli.py:340
msgid "&Cancel"
msgstr "&Peruuta"

#: ../bin/apport-cli.py:238 ../debian/tmp/usr/bin/apport-cli.py:238
msgid "Problem report file:"
msgstr "Ongelmaraporttitiedosto:"

#: ../bin/apport-cli.py:244 ../bin/apport-cli.py:249
#: ../debian/tmp/usr/bin/apport-cli.py:244
#: ../debian/tmp/usr/bin/apport-cli.py:249
msgid "&Confirm"
msgstr "&Vahvista"

#: ../bin/apport-cli.py:248 ../debian/tmp/usr/bin/apport-cli.py:248
#, python-format
msgid "Error: %s"
msgstr "Virhe: %s"

#: ../kde/apport-kde.py:407 ../bin/apport-cli.py:254
#: ../debian/tmp/usr/share/apport/apport-kde.py:407
#: ../debian/tmp/usr/bin/apport-cli.py:254
msgid "Collecting problem information"
msgstr "Kerätään tietoja ongelmasta"

#: ../bin/apport-cli.py:255 ../debian/tmp/usr/bin/apport-cli.py:255
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Kerätyt tiedot voidaan lähettää kehittäjille ohjelman parantamiseksi.\n"
"Tähän voi mennä muutama minuutti."

#: ../bin/apport-cli.py:268 ../debian/tmp/usr/bin/apport-cli.py:268
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Kerätyt tiedot lähetetään virheseurantajärjestelmään.\n"
"Tähän voi mennä muutama minuutti."

#: ../bin/apport-cli.py:318 ../debian/tmp/usr/bin/apport-cli.py:318
msgid "&Done"
msgstr "&Valmis"

#: ../bin/apport-cli.py:324 ../debian/tmp/usr/bin/apport-cli.py:324
msgid "none"
msgstr "ei mitään"

#: ../bin/apport-cli.py:325 ../debian/tmp/usr/bin/apport-cli.py:325
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Valittu: %s. Useita valintoja:"

#: ../bin/apport-cli.py:341 ../debian/tmp/usr/bin/apport-cli.py:341
msgid "Choices:"
msgstr "Valinnat:"

#: ../bin/apport-cli.py:355 ../debian/tmp/usr/bin/apport-cli.py:355
msgid "Path to file (Enter to cancel):"
msgstr "Polku tiedostoon (Enter peruu):"

#: ../bin/apport-cli.py:361 ../debian/tmp/usr/bin/apport-cli.py:361
msgid "File does not exist."
msgstr "Tiedostoa ei ole olemassa."

#: ../bin/apport-cli.py:363 ../debian/tmp/usr/bin/apport-cli.py:363
msgid "This is a directory."
msgstr "Tämä on hakemisto."

#: ../bin/apport-cli.py:369 ../debian/tmp/usr/bin/apport-cli.py:369
msgid "To continue, you must visit the following URL:"
msgstr "Jatkaaksesi sinun tulee käydä seuraavassa URL-osoitteessa:"

#: ../bin/apport-cli.py:371 ../debian/tmp/usr/bin/apport-cli.py:371
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Voit nyt käynnistää selaimen tai kopioida tämän URL-osoitteen selaimeen "
"toisella tietokoneella."

#: ../bin/apport-cli.py:373 ../debian/tmp/usr/bin/apport-cli.py:373
msgid "Launch a browser now"
msgstr "Käynnistä selain nyt"

#: ../bin/apport-cli.py:388 ../debian/tmp/usr/bin/apport-cli.py:388
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"Ei odottavia kaatumisraportteja. Kokeile --help saadaksesi lisäinformaatiota."

#: ../data/apportcheckresume.py:67
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"Tämä tapahtui edellisen valmiustilan aikana ja esti järjestelmää "
"palautumasta oikein."

#: ../data/apportcheckresume.py:69
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"Tämä tapahtui edellisen lepotilan aikana ja esti järjestelmää palautumasta "
"oikein."

#: ../data/apportcheckresume.py:74
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Aloitettu ajo jumiutui erittäin lähellä loppua ja tulee ilmestymään "
"suorittuakseen loppuun normaalisti."

#: ../kde/apport-kde.py:234 ../debian/tmp/usr/share/apport/apport-kde.py:234
msgid "Leave Closed"
msgstr "Sulje sovellus"

#: ../kde/apport-kde.py:235 ../kde/apport-kde.py:381
#: ../debian/tmp/usr/share/apport/apport-kde.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:381
msgid "Relaunch"
msgstr "Käynnistä uudelleen"

#: ../kde/apport-kde.py:315 ../debian/tmp/usr/share/apport/apport-kde.py:315
msgid "Username:"
msgstr "Käyttäjätunnus:"

#: ../kde/apport-kde.py:316 ../debian/tmp/usr/share/apport/apport-kde.py:316
msgid "Password:"
msgstr "Salasana:"

#: ../kde/apport-kde.py:406 ../debian/tmp/usr/share/apport/apport-kde.py:406
msgid "Collecting Problem Information"
msgstr "Kerätään tietoja ongelmasta"

#: ../kde/apport-kde.py:408 ../debian/tmp/usr/share/apport/apport-kde.py:408
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Kerätty tieto voidaan lähettää kehittäjille ohjelmiston parantamiseksi. Tämä "
"voi kestää muutamia minuutteja."

#: ../kde/apport-kde.py:434 ../debian/tmp/usr/share/apport/apport-kde.py:434
msgid "Uploading Problem Information"
msgstr "Lähetetään tiedot ongelmasta"

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "Voit auttaa kehittäjiä korjaaman ongelman ilmoittamalla siitä."

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "Paketin \"%s\" asennus tai päivitys epäonnistui."

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Täydellinen raportti (suositus; %s)"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Lähetetäänkö ongelmaraportti sovelluksen kehittäjille?</b></big>\n"
#~ "\n"
#~ "Ole hyvä ja täytä automaattisesti selaimeen auennut lomake, kun "
#~ "ongelmaraportti on lähetetty."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "Jos et tehnyt mitään luottamuksellista (syöttänyt salasanoja tai muita "
#~ "henkilökohtaisia tietoja), voit auttaa kehittämään ohjelmaa raportoimalla "
#~ "ongelmasta."

#, python-format
#~ msgid "Sorry, %s closed unexpectedly"
#~ msgstr "Ikävä kyllä %s sulkeutui yllättäen"

#~ msgid "Application problem"
#~ msgstr "Ongelma sovelluksessa"

#~ msgid "&Details..."
#~ msgstr "&Yksityiskohdat..."

#~ msgid "_Send Report"
#~ msgstr "_Lähetä raportti"

#~ msgid "Generic error"
#~ msgstr "Yleinen virhe"

#~ msgid ""
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "Kun raportti on lähetetty, ole hyvä ja täytä selaimeesi automaattisesti "
#~ "aukeava lomake."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Jos et ollut tekemässä mitään luottamuksellista (kuten syöttänyt salasanoja "
#~ "tai muuta\n"
#~ "henkilökohtaista tietoa), voit auttaa ohjelman kehittämisessä raportoimalla\n"
#~ "ongelman."

#~ msgid "Restart _Program"
#~ msgstr "Uudelleenkäynnistä _ohjelma"

#, python-format
#~ msgid "Sorry, the package \"%s\" failed to install or upgrade."
#~ msgstr "Ikävä kyllä paketin \"%s\" asennus tai päivitys epäonnistui."

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">Paketin \"%s\" asennus tai päivitys "
#~ "epäonnistui.</span>"

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Lähetä täydellinen raportti (suositeltavaa; %s)"

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Pelkistetty raportti (hidas Internet-yhteys; %s)"

#, python-format
#~ msgid "Sorry, %s closed unexpectedly."
#~ msgstr "Ikävä kyllä %s sulkeutui yllättäen."

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Jätä tämän ohjelmaversion kaatumiset huomiotta jatkossa"

#~ msgid "Restart &Program"
#~ msgstr "Käynnistä &ohjelma uudelleen"

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Lähetä &suppea raportti (hitaille Internet-yhteyksille; %s)"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "Tämä poistaa joitain isoimpia osuuksia raportista. Osuudet ovat hyödyllisiä "
#~ "ohjelman kehittäjille ongelman selvittämisessä mutta et välttämättä halua "
#~ "odottaa niiden lähettämistä, jos Internet-yhteytesi on hidas."

#~ msgid "&Report Problem..."
#~ msgstr "&Raportoi ongelma..."

#~ msgid "The report belongs to a package that is not installed."
#~ msgstr "Raportti liittyy pakettiin, jota ei ole asennettu."

#~ msgid "_Report Problem..."
#~ msgstr "_Raportoi ongelma..."

#~ msgid "&Send"
#~ msgstr "&Lähetä"

#~ msgid "Kernel problem"
#~ msgstr "Ongelma käyttöjärjestelmän ytimessä"

#~ msgid "&Ignore future crashes of this program version"
#~ msgstr "Älä huomioi tämän ohjelmaversion kaatumisia jatkossa"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr "Voi auttaa kehittäjiä korjaamaan ongelman raportoimalla ongelmasta."

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "Tämä ei ole alkuperäinen %s-paketti"

#, python-format
#~ msgid "Sorry, the program \"%s\" closed unexpectedly."
#~ msgstr "Ikävä kyllä ohjelma \"%s\" sulkeutui yllättäen."

#~ msgid "Content of the report"
#~ msgstr "Raportin sisältö"

#~ msgid "Package problem"
#~ msgstr "Ongelma paketissa"

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "Järjestelmässä tapahtui vakava ydinongelma."

#~ msgid ""
#~ "This occured during a previous suspend and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Tämä tapahtui viimeisen keskeytyksen aikana ja esti sitä jatkamasta "
#~ "asianmukaisesti."

#~ msgid ""
#~ "This occured during a previous hibernate and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Tämä tapahtui viimeisen horrostilan aikana ja esti sitä jatkamasta "
#~ "asianmukaisesti."

#~ msgid "incorrect number of arguments; use --help for a short help"
#~ msgstr ""
#~ "virheellinen lukumäärä argumentteja; käytä --help:iä saadaksesi lyhyesti apua"

#~ msgid ""
#~ "you either need to do a local operation (-s, -g, -o) or supply an "
#~ "authentication file (--auth); see --help for a short help"
#~ msgstr ""
#~ "sinun tarvitsee tehdä joko paikallinen operaatio (-s, -g, -o) tai toimittaa "
#~ "varmennustiedosto (--auth); katso --help saadaksesi lyhyesti apua"

#~ msgid "Send this data to the developers?"
#~ msgstr "Lähetetäänkö nämä tiedot kehittäjille?"

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s sulkeutui yllättäen %s %s."

#~ msgid "%prog [options] <apport problem report | crash ID>"
#~ msgstr "%prog [valinnat] <tasaa ongelmaraportti | kaatumistunniste>"

#, python-format
#~ msgid "Sorry, the application %s has closed unexpectedly."
#~ msgstr "Valitettavasti sovellus %s sulkeutui odottamatta."

#~ msgid "Send an error report to help fix this problem"
#~ msgstr "Auta kehittäjiä korjaamaan tämä ongelma lähettämällä vikailmoitus"

#~ msgid "Force Closed"
#~ msgstr "Suljettu väkisin"

#~ msgid "Your system might become unstablenow and might need to be restarted."
#~ msgstr ""
#~ "Järjestelmäsi saattaa tulla epävakaaksi ja vaatia uudelleenkäynnistystä."
