# Armenian translation for apport
# Copyright (c) 2011 Rosetta Contributors and Canonical Ltd 2011
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-09-17 15:41-0500\n"
"PO-Revision-Date: 2011-10-07 06:10+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Armenian <hy@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-09-18 04:41+0000\n"
"X-Generator: Launchpad (build 16765)\n"
"Language: hy\n"

#: ../apport/ui.py:124
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:124
msgid "This package does not seem to be installed correctly"
msgstr ""

#: ../apport/ui.py:128
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:128
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""

#: ../apport/ui.py:145
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:145
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""

#: ../apport/ui.py:251
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:251
msgid "unknown program"
msgstr ""

#: ../apport/ui.py:252
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:252
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr ""

#: ../apport/ui.py:254 ../apport/ui.py:1263
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:254
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1263
#, python-format
msgid "Problem in %s"
msgstr ""

#: ../apport/ui.py:255
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:255
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""

#. package does not exist
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:274
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1046
#: ../apport/ui.py:270 ../apport/ui.py:276 ../apport/ui.py:282
#: ../apport/ui.py:325 ../apport/ui.py:333 ../apport/ui.py:460
#: ../apport/ui.py:463 ../apport/ui.py:664 ../apport/ui.py:1094
#: ../apport/ui.py:1235 ../apport/ui.py:1239
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:270
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:276
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:282
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:325
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:333
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:460
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:463
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:664
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1094
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1235
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1239
msgid "Invalid problem report"
msgstr ""

#: ../apport/ui.py:271 ../apport/ui.py:1241
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:271
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1241
msgid "This problem report is damaged and cannot be processed."
msgstr ""

#: ../apport/ui.py:277
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:277
msgid "The report belongs to a package that is not installed."
msgstr ""

#: ../apport/ui.py:283
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:283
msgid "An error occurred while attempting to process this problem report:"
msgstr ""

#: ../apport/ui.py:326
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:326
msgid "You are not allowed to access this problem report."
msgstr ""

#: ../apport/ui.py:329
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:329
msgid "Error"
msgstr ""

#: ../apport/ui.py:330
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:330
msgid "There is not enough disk space available to process this report."
msgstr ""

#: ../apport/ui.py:414
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:414
msgid "No package specified"
msgstr ""

#: ../apport/ui.py:415
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:415
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""

#: ../apport/ui.py:438
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:438
msgid "Permission denied"
msgstr ""

#: ../apport/ui.py:439
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:439
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""

#: ../apport/ui.py:441
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:441
msgid "Invalid PID"
msgstr ""

#: ../apport/ui.py:442
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:442
msgid "The specified process ID does not belong to a program."
msgstr ""

#: ../apport/ui.py:461
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:461
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../apport/ui.py:464
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:464
#, python-format
msgid "Package %s does not exist"
msgstr ""

#: ../apport/ui.py:488 ../apport/ui.py:676 ../apport/ui.py:681
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:488
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:676
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:681
msgid "Cannot create report"
msgstr ""

#: ../apport/ui.py:503 ../apport/ui.py:549 ../apport/ui.py:566
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:503
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:549
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:566
msgid "Updating problem report"
msgstr ""

#: ../apport/ui.py:504
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:504
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""

#: ../apport/ui.py:513
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:513
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""

#: ../apport/ui.py:550 ../apport/ui.py:567
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:550
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:567
msgid "No additional information collected."
msgstr ""

#: ../apport/ui.py:618
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:618
msgid "What kind of problem do you want to report?"
msgstr ""

#: ../apport/ui.py:635
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:635
msgid "Unknown symptom"
msgstr ""

#: ../apport/ui.py:636
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:636
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr ""

#: ../apport/ui.py:667
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:667
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""

#: ../apport/ui.py:677 ../apport/ui.py:682
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:677
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:682
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../apport/ui.py:696
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:696
msgid "%prog <report number>"
msgstr ""

#: ../apport/ui.py:698
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:698
msgid "Specify package name."
msgstr ""

#: ../apport/ui.py:700 ../apport/ui.py:751
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:700
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:751
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../apport/ui.py:730
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:730
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../apport/ui.py:733
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:733
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../apport/ui.py:735
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:735
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../apport/ui.py:737
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:737
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../apport/ui.py:739
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:739
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:741
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:741
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../apport/ui.py:743
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:743
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:745
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:745
msgid "The provided pid is a hanging application."
msgstr ""

#: ../apport/ui.py:747
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:747
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../apport/ui.py:749
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:749
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../apport/ui.py:753
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:753
msgid "Print the Apport version number."
msgstr ""

#: ../apport/ui.py:893
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:893
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../apport/ui.py:894
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:894
msgid "Run gdb session"
msgstr ""

#: ../apport/ui.py:895
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:895
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:897
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:897
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../apport/ui.py:972 ../apport/ui.py:982
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:972
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:982
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""

#: ../apport/ui.py:997
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:997
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""

#: ../apport/ui.py:1095
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1095
msgid "Could not determine the package or source package name."
msgstr ""

#: ../apport/ui.py:1113
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1113
msgid "Unable to start web browser"
msgstr ""

#: ../apport/ui.py:1114
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1114
#, python-format
msgid "Unable to start web browser to open %s."
msgstr ""

#: ../apport/ui.py:1189
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1189
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""

#: ../apport/ui.py:1201
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1201
msgid "Network problem"
msgstr ""

#: ../apport/ui.py:1203
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1203
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""

#: ../apport/ui.py:1230
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1230
msgid "Memory exhaustion"
msgstr ""

#: ../apport/ui.py:1231
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1231
msgid "Your system does not have enough memory to process this crash report."
msgstr ""

#: ../apport/ui.py:1266
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1266
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""

#: ../apport/ui.py:1322 ../apport/ui.py:1329
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1322
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1329
msgid "Problem already known"
msgstr ""

#: ../apport/ui.py:1323
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1323
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""

#: ../apport/ui.py:1330
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1330
msgid "This problem was already reported to developers. Thank you!"
msgstr ""

#: ../bin/apport-cli.py:74 ../debian/tmp/usr/bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr ""

#: ../bin/apport-cli.py:81 ../debian/tmp/usr/bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr ""

#: ../bin/apport-cli.py:85 ../debian/tmp/usr/bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr ""

#: ../bin/apport-cli.py:145 ../debian/tmp/usr/bin/apport-cli.py:145
#, python-format
msgid "(%i bytes)"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:338
#: ../debian/tmp/usr/share/apport/apport-gtk.py:138 ../bin/apport-cli.py:147
#: ../debian/tmp/usr/bin/apport-cli.py:147 ../gtk/apport-gtk.py:138
#: ../kde/apport-kde.py:338
msgid "(binary data)"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:162
#: ../debian/tmp/usr/share/apport/apport-gtk.py:173 ../bin/apport-cli.py:175
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:404
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:429
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:286
#: ../debian/tmp/usr/bin/apport-cli.py:175 ../gtk/apport-gtk.py:173
#: ../kde/apport-kde.py:162
msgid "Send problem report to the developers?"
msgstr ""

#: ../bin/apport-cli.py:176 ../debian/tmp/usr/bin/apport-cli.py:176
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""

#: ../bin/apport-cli.py:179 ../debian/tmp/usr/bin/apport-cli.py:179
#, python-format
msgid "&Send report (%s)"
msgstr ""

#: ../bin/apport-cli.py:183 ../debian/tmp/usr/bin/apport-cli.py:183
msgid "&Examine locally"
msgstr ""

#: ../bin/apport-cli.py:187 ../debian/tmp/usr/bin/apport-cli.py:187
msgid "&View report"
msgstr ""

#: ../bin/apport-cli.py:188 ../debian/tmp/usr/bin/apport-cli.py:188
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""

#: ../bin/apport-cli.py:189 ../debian/tmp/usr/bin/apport-cli.py:189
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""

#: ../bin/apport-cli.py:191 ../bin/apport-cli.py:268 ../bin/apport-cli.py:300
#: ../bin/apport-cli.py:321 ../debian/tmp/usr/bin/apport-cli.py:191
#: ../debian/tmp/usr/bin/apport-cli.py:268
#: ../debian/tmp/usr/bin/apport-cli.py:300
#: ../debian/tmp/usr/bin/apport-cli.py:321
msgid "&Cancel"
msgstr ""

#: ../bin/apport-cli.py:219 ../debian/tmp/usr/bin/apport-cli.py:219
msgid "Problem report file:"
msgstr ""

#: ../bin/apport-cli.py:225 ../bin/apport-cli.py:230
#: ../debian/tmp/usr/bin/apport-cli.py:225
#: ../debian/tmp/usr/bin/apport-cli.py:230
msgid "&Confirm"
msgstr ""

#: ../bin/apport-cli.py:229 ../debian/tmp/usr/bin/apport-cli.py:229
#, python-format
msgid "Error: %s"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:383 ../bin/apport-cli.py:235
#: ../debian/tmp/usr/bin/apport-cli.py:235 ../kde/apport-kde.py:383
msgid "Collecting problem information"
msgstr ""

#: ../bin/apport-cli.py:236 ../debian/tmp/usr/bin/apport-cli.py:236
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:411
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../bin/apport-cli.py:248
#: ../gtk/apport-gtk.ui.h:13 ../debian/tmp/usr/bin/apport-cli.py:248
#: ../kde/apport-kde.py:411
msgid "Uploading problem information"
msgstr ""

#: ../bin/apport-cli.py:249 ../debian/tmp/usr/bin/apport-cli.py:249
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""

#: ../bin/apport-cli.py:299 ../debian/tmp/usr/bin/apport-cli.py:299
msgid "&Done"
msgstr ""

#: ../bin/apport-cli.py:305 ../debian/tmp/usr/bin/apport-cli.py:305
msgid "none"
msgstr ""

#: ../bin/apport-cli.py:306 ../debian/tmp/usr/bin/apport-cli.py:306
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr ""

#: ../bin/apport-cli.py:322 ../debian/tmp/usr/bin/apport-cli.py:322
msgid "Choices:"
msgstr ""

#: ../bin/apport-cli.py:336 ../debian/tmp/usr/bin/apport-cli.py:336
msgid "Path to file (Enter to cancel):"
msgstr ""

#: ../bin/apport-cli.py:342 ../debian/tmp/usr/bin/apport-cli.py:342
msgid "File does not exist."
msgstr ""

#: ../bin/apport-cli.py:344 ../debian/tmp/usr/bin/apport-cli.py:344
msgid "This is a directory."
msgstr ""

#: ../bin/apport-cli.py:350 ../debian/tmp/usr/bin/apport-cli.py:350
msgid "To continue, you must visit the following URL:"
msgstr ""

#: ../bin/apport-cli.py:352 ../debian/tmp/usr/bin/apport-cli.py:352
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""

#: ../bin/apport-cli.py:354 ../debian/tmp/usr/bin/apport-cli.py:354
msgid "Launch a browser now"
msgstr ""

#: ../bin/apport-cli.py:368 ../debian/tmp/usr/bin/apport-cli.py:368
msgid "No pending crash reports. Try --help for more information."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:68
#: ../data/apportcheckresume.py:68
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:70
#: ../data/apportcheckresume.py:70
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:75
#: ../data/apportcheckresume.py:75
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""

#: ../bin/apport-retrace.py:31 ../debian/tmp/usr/bin/apport-retrace.py:31
msgid "%prog [options] <apport problem report | crash ID>"
msgstr ""

#: ../bin/apport-retrace.py:33 ../debian/tmp/usr/bin/apport-retrace.py:33
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../bin/apport-retrace.py:35 ../debian/tmp/usr/bin/apport-retrace.py:35
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../bin/apport-retrace.py:37 ../debian/tmp/usr/bin/apport-retrace.py:37
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""

#: ../bin/apport-retrace.py:39 ../debian/tmp/usr/bin/apport-retrace.py:39
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Override report's CoreFile"
msgstr ""

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid "Override report's ExecutablePath"
msgstr ""

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid "Override report's ProcMaps"
msgstr ""

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Rebuild report's Package information"
msgstr ""

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-valgrind.py:66 ../bin/apport-retrace.py:59
#: ../debian/tmp/usr/bin/apport-retrace.py:59
#: ../debian/tmp/usr/bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../bin/apport-retrace.py:63 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../bin/apport-retrace.py:65 ../debian/tmp/usr/bin/apport-retrace.py:65
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../bin/apport-retrace.py:70 ../debian/tmp/usr/bin/apport-retrace.py:70
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""

#: ../bin/apport-retrace.py:76 ../debian/tmp/usr/bin/apport-retrace.py:76
msgid "You cannot use -C without -S. Stopping."
msgstr ""

#: ../bin/apport-retrace.py:80 ../debian/tmp/usr/bin/apport-retrace.py:80
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:114 ../debian/tmp/usr/bin/apport-retrace.py:114
msgid "OK to send these as attachments? [y/n]"
msgstr ""

#: ../kde/apport-kde.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr ""

#: ../kde/apport-kde.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr ""

#: ../data/kernel_oops.py:28 ../debian/tmp/usr/share/apport/kernel_oops.py:28
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:153 ../gtk/apport-gtk.py:153
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:156 ../gtk/apport-gtk.py:156
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:176
#: ../debian/tmp/usr/share/apport/apport-kde.py:217
#: ../debian/tmp/usr/share/apport/apport-gtk.py:161
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:108
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:300
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:110
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:254
#: ../gtk/apport-gtk.py:161 ../kde/apport-kde.py:176 ../kde/apport-kde.py:217
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:170
#: ../debian/tmp/usr/share/apport/apport-gtk.py:182
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:412
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:437
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:292
#: ../gtk/apport-gtk.py:182 ../kde/apport-kde.py:170
msgid "Send"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:271
#: ../debian/tmp/usr/share/apport/apport-gtk.py:200
#: ../debian/tmp/usr/share/apport/apport-gtk.py:569
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7 ../gtk/apport-gtk.ui.h:7
#: ../gtk/apport-gtk.py:200 ../gtk/apport-gtk.py:569 ../kde/apport-kde.py:271
msgid "Show Details"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:210
#: ../debian/tmp/usr/share/apport/apport-kde.py:223
#: ../debian/tmp/usr/share/apport/apport-gtk.py:212
#: ../debian/tmp/usr/share/apport/apport-gtk.py:280
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:144
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:157
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:192
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:310
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:350
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:479
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:141
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:153
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:186
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:262
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:332
#: ../gtk/apport-gtk.ui.h:10 ../gtk/apport-gtk.py:212 ../gtk/apport-gtk.py:280
#: ../gtk/apport-gtk.py:299 ../kde/apport-kde.py:210 ../kde/apport-kde.py:223
msgid "Continue"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:224
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:276
#: ../gtk/apport-gtk.py:224
msgid "Force Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-kde.py:357
#: ../debian/tmp/usr/share/apport/apport-gtk.py:225
#: ../debian/tmp/usr/share/apport/apport-gtk.py:284
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:232
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:273
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:226
#: ../gtk/apport-gtk.py:225 ../gtk/apport-gtk.py:284 ../kde/apport-kde.py:214
#: ../kde/apport-kde.py:357
msgid "Relaunch"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:234 ../gtk/apport-gtk.py:234
#, python-format
msgid "The application %s has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:238 ../gtk/apport-gtk.py:238
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:184
#: ../debian/tmp/usr/share/apport/apport-gtk.py:253 ../gtk/apport-gtk.py:253
#: ../kde/apport-kde.py:184
#, python-format
msgid "Package: %s"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:190
#: ../debian/tmp/usr/share/apport/apport-gtk.py:260
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:137
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:136
#: ../gtk/apport-gtk.py:260 ../kde/apport-kde.py:190
msgid "Sorry, a problem occurred while installing software."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:197
#: ../debian/tmp/usr/share/apport/apport-gtk.py:269
#: ../debian/tmp/usr/share/apport/apport-gtk.py:288 ../gtk/apport-gtk.py:269
#: ../gtk/apport-gtk.py:288 ../kde/apport-kde.py:197
#, python-format
msgid "The application %s has experienced an internal error."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:201
#: ../debian/tmp/usr/share/apport/apport-gtk.py:272 ../gtk/apport-gtk.py:272
#: ../kde/apport-kde.py:201
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:213
#: ../debian/tmp/usr/share/apport/apport-gtk.py:283
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9 ../gtk/apport-gtk.ui.h:9
#: ../gtk/apport-gtk.py:283 ../kde/apport-kde.py:213
msgid "Leave Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/apport-gtk.py:296
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:302
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:342
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:256
#: ../gtk/apport-gtk.ui.h:4 ../gtk/apport-gtk.py:296 ../kde/apport-kde.py:220
msgid "If you notice further problems, try restarting the computer."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:224
#: ../debian/tmp/usr/share/apport/apport-gtk.py:300 ../gtk/apport-gtk.py:300
#: ../kde/apport-kde.py:224
msgid "Ignore future problems of this type"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:268
#: ../debian/tmp/usr/share/apport/apport-gtk.py:573 ../gtk/apport-gtk.py:573
#: ../kde/apport-kde.py:268
msgid "Hide Details"
msgstr ""

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr ""

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:294 ../kde/apport-kde.py:294
msgid "Username:"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:295 ../kde/apport-kde.py:295
msgid "Password:"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:382 ../kde/apport-kde.py:382
msgid "Collecting Problem Information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:384 ../kde/apport-kde.py:384
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:410 ../kde/apport-kde.py:410
msgid "Uploading Problem Information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:412
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../gtk/apport-gtk.ui.h:15
#: ../kde/apport-kde.py:412
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:446
#: ../debian/tmp/usr/share/apport/apport-kde.py:482
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:446 ../kde/apport-kde.py:482
msgid "Apport"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Crash report"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6 ../gtk/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11 ../gtk/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../gtk/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14 ../gtk/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr ""

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr ""

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr ""

#: ../debian/tmp/usr/bin/apport-unpack.py:46 ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr ""
