# Icelandic translation for apport
# Copyright (c) 2008 Rosetta Contributors and Canonical Ltd 2008
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2008.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-05-17 09:15-0700\n"
"PO-Revision-Date: 2015-04-27 21:46+0000\n"
"Last-Translator: Páll Haraldsson <Pall.Haraldsson@gmail.com>\n"
"Language-Team: Icelandic <is@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2020-10-02 05:45+0000\n"
"X-Generator: Launchpad (build d50d1e75c500726862802414f880ee3e3bb759bf)\n"
"Language: is\n"

#: ../kde/apport-kde-mime.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Tilkynna vandamál..."

#: ../kde/apport-kde-mime.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Tilkynna bilun til forritara"

#: ../debian/tmp/usr/share/apport/apport-kde.py:363
#: ../debian/tmp/usr/bin/apport-cli.py:166
#: ../debian/tmp/usr/share/apport/apport-gtk.py:146 ../gtk/apport-gtk.py:146
#: ../bin/apport-cli.py:166 ../kde/apport-kde.py:363
msgid "(binary data)"
msgstr "(gögn í tvíundakerfi)"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:161 ../gtk/apport-gtk.py:161
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Því miður, forritið %s hætti óvænt."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:164 ../gtk/apport-gtk.py:164
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Því miður, forritið %s lokaði óvænt."

#: ../debian/tmp/usr/share/apport/apport-kde.py:200
#: ../debian/tmp/usr/share/apport/apport-kde.py:238
#: ../debian/tmp/usr/share/apport/apport-gtk.py:169 ../gtk/apport-gtk.py:169
#: ../kde/apport-kde.py:200 ../kde/apport-kde.py:238
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Því miður, %s hefur lent í innri villu."

#: ../debian/tmp/usr/share/apport/apport-kde.py:186
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
#: ../debian/tmp/usr/bin/apport-cli.py:194
#: ../debian/tmp/usr/share/apport/apport-gtk.py:181 ../gtk/apport-gtk.ui.h:6
#: ../gtk/apport-gtk.py:181 ../bin/apport-cli.py:194 ../kde/apport-kde.py:186
msgid "Send problem report to the developers?"
msgstr "Senda vandamálsskýrslu til forritara?"

#: ../debian/tmp/usr/share/apport/apport-kde.py:194
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
#: ../debian/tmp/usr/share/apport/apport-gtk.py:188 ../gtk/apport-gtk.ui.h:14
#: ../gtk/apport-gtk.py:188 ../kde/apport-kde.py:194
msgid "Send"
msgstr "Senda"

#: ../debian/tmp/usr/share/apport/apport-kde.py:292
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:575 ../gtk/apport-gtk.ui.h:11
#: ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:575 ../kde/apport-kde.py:292
msgid "Show Details"
msgstr "Sýna ítarlegri upplýsingar"

#: ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-kde.py:244
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216 ../gtk/apport-gtk.py:216
#: ../kde/apport-kde.py:231 ../kde/apport-kde.py:244
msgid "Continue"
msgstr "Halda áfram"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:239 ../gtk/apport-gtk.py:239
#, python-format
msgid "The application %s has stopped responding."
msgstr "Forritið %s hætti að svara."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:243 ../gtk/apport-gtk.py:243
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Forritið %s hætti að svara."

#: ../debian/tmp/usr/share/apport/apport-kde.py:208
#: ../debian/tmp/usr/share/apport/apport-gtk.py:259 ../gtk/apport-gtk.py:259
#: ../kde/apport-kde.py:208
#, python-format
msgid "Package: %s"
msgstr "Pakki: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-gtk.py:265 ../gtk/apport-gtk.py:265
#: ../kde/apport-kde.py:214
msgid "Sorry, a problem occurred while installing software."
msgstr "Því miður, vandamál kom upp við upppsetningu hugbúnaðar."

#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/apport-gtk.py:274
#: ../debian/tmp/usr/share/apport/apport-gtk.py:289 ../gtk/apport-gtk.py:274
#: ../gtk/apport-gtk.py:289 ../kde/apport-kde.py:220
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "Forritið %s lenti í innri villu."

#: ../debian/tmp/usr/share/apport/apport-kde.py:223
#: ../debian/tmp/usr/share/apport/apport-gtk.py:277 ../gtk/apport-gtk.py:277
#: ../kde/apport-kde.py:223
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Forritið %s lokaði óvænt."

#: ../debian/tmp/usr/share/apport/apport-kde.py:241
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297 ../gtk/apport-gtk.ui.h:7
#: ../gtk/apport-gtk.py:297 ../kde/apport-kde.py:241
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"Ef þú verður var við fleiri vandamál, reyndu þá að endurræsa tölvuna."

#: ../debian/tmp/usr/share/apport/apport-kde.py:245
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299 ../gtk/apport-gtk.py:299
#: ../kde/apport-kde.py:245
msgid "Ignore future problems of this type"
msgstr "Hunsa svona vandamál héðan í frá"

#: ../debian/tmp/usr/share/apport/apport-kde.py:289
#: ../debian/tmp/usr/share/apport/apport-gtk.py:579 ../gtk/apport-gtk.py:579
#: ../kde/apport-kde.py:289
msgid "Hide Details"
msgstr "Fela nánari upplýsingar"

#: ../bin/apport-retrace.py:34 ../debian/tmp/usr/bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../bin/apport-retrace.py:36 ../debian/tmp/usr/bin/apport-retrace.py:36
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../bin/apport-retrace.py:38 ../debian/tmp/usr/bin/apport-retrace.py:38
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr ""

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr ""

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr ""

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr ""

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../bin/apport-retrace.py:59 ../debian/tmp/usr/bin/apport-retrace.py:59
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../bin/apport-retrace.py:63 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-retrace.py:65 ../bin/apport-valgrind.py:66
#: ../debian/tmp/usr/bin/apport-retrace.py:65
#: ../debian/tmp/usr/bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-retrace.py:67 ../debian/tmp/usr/bin/apport-retrace.py:67
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../bin/apport-retrace.py:69 ../debian/tmp/usr/bin/apport-retrace.py:69
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../bin/apport-retrace.py:71 ../debian/tmp/usr/bin/apport-retrace.py:71
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../bin/apport-retrace.py:73 ../debian/tmp/usr/bin/apport-retrace.py:73
msgid "Do not add StacktraceSource to the report."
msgstr ""

#: ../bin/apport-retrace.py:82 ../debian/tmp/usr/bin/apport-retrace.py:82
msgid "You cannot use -C without -S. Stopping."
msgstr "Þú getur ekki notað -C án -S. Hætti."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:115 ../debian/tmp/usr/bin/apport-retrace.py:115
msgid "OK to send these as attachments? [y/n]"
msgstr "Er allt í lagi að senda þetta sem sem viðhengi? [y/n]"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport villuskrá"

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Sjá nánar á man-síðu."

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"endurnýta sandkassamöppu (SDIR) sem þegar hefur verið búin til eða, ef hún "
"er ekki til, búa hana til"

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"ekki búa til né endurnýta sandkassamöppu fyrir auka aflúsunarmerki heldur "
"aðeins treysta á uppsett aflúsunarmerki."

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"endurnýta skyndiminnismöppu (CDIR) sem þegar hefur verið búin til eða, ef "
"hún er ekki til, búa hana til"

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Villa: %s er ekki keyranlegt forrit. Hætti."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:139
#: ../apport/ui.py:139
msgid "This package does not seem to be installed correctly"
msgstr "Þessi pakki virðist ekki rétt upp settur"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:130
#: ../apport/ui.py:130
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:166
#: ../apport/ui.py:166
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Þú er með uppsettar einhverjar úreltar útgáfur af pökkum. Endilega uppfærðu "
"eftirfarandi pakka og athugaðu hvort vandamálið endurtekur sig:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:303
#: ../apport/ui.py:303
msgid "unknown program"
msgstr "óþekkt forrit"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:304
#: ../apport/ui.py:304
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Fyrirgefðu, forritið \"%s\" hætti óvænt"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:306
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1458
#: ../apport/ui.py:306 ../apport/ui.py:1458
#, python-format
msgid "Problem in %s"
msgstr "Vandamál í %s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:307
#: ../apport/ui.py:307
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Tölvan þín hefur ekki nóg laust innra minni til að greina sjálfkrafa "
"vandamálið og senda til forritaranna."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:362
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:370
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:519
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:522
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:727
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1264
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1430
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1434
#: ../apport/ui.py:362 ../apport/ui.py:370 ../apport/ui.py:519
#: ../apport/ui.py:522 ../apport/ui.py:727 ../apport/ui.py:1264
#: ../apport/ui.py:1430 ../apport/ui.py:1434
msgid "Invalid problem report"
msgstr "Ógild vandamálsskýrsla"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:363
#: ../apport/ui.py:363
msgid "You are not allowed to access this problem report."
msgstr "Þú hefur ekki leyfi til að skoða þessa skýrslu."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:366
#: ../apport/ui.py:366
msgid "Error"
msgstr "Villa"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:367
#: ../apport/ui.py:367
msgid "There is not enough disk space available to process this report."
msgstr "Það er ekki nóg diskpláss til að vinna úr skýrslunni."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:411
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:500
#: ../apport/ui.py:411 ../apport/ui.py:500
msgid "Invalid PID"
msgstr "Ógilt PID"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:412
#: ../apport/ui.py:412
msgid "The specified process ID does not exist."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:415
#: ../apport/ui.py:415
msgid "Not your PID"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:416
#: ../apport/ui.py:416
msgid "The specified process ID does not belong to you."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:467
#: ../apport/ui.py:467
msgid "No package specified"
msgstr "Enginn pakki valinn"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:468
#: ../apport/ui.py:468
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Þú þarft að tilgreina pakka eða PID. Sjá --help fyrir meiri upplýsingar."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:497
#: ../apport/ui.py:497
msgid "Permission denied"
msgstr "Aðgangur bannaður"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:498
#: ../apport/ui.py:498
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Tiltekið ferli tilheyrir þér ekki. Keyrðu þetta forrit sem eigandi ferlisins "
"eða sem kerfisstjórnandi"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:501
#: ../apport/ui.py:501
msgid "The specified process ID does not belong to a program."
msgstr "Þetta ID tilheyrir ekki neinu forriti."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:520
#: ../apport/ui.py:520
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:523
#: ../apport/ui.py:523
#, python-format
msgid "Package %s does not exist"
msgstr "Pakki %s er ekki til"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:739
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:744
#: ../apport/ui.py:552 ../apport/ui.py:739 ../apport/ui.py:744
msgid "Cannot create report"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:567
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:613
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:629
#: ../apport/ui.py:567 ../apport/ui.py:613 ../apport/ui.py:629
msgid "Updating problem report"
msgstr "Uppfæri villuskýrslu"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:568
#: ../apport/ui.py:568
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Þú ert ekki tilkynnandi eða áskrifandi að þessarri villuskýrslu, eða "
"skýrslan er tvítekin eða nú þegar lokuð.\n"
"\n"
"Búðu til nýja skýrslu með ‚apport-bug‘."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:577
#: ../apport/ui.py:577
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Þú ert ekki tilkynnandi þessarar villuskýrslu. Mun auðveldara er að merkja "
"villu sem tvítekningu annarrar heldur en að færa athugasemdir og viðhengin "
"þín í nýja villu.\n"
"\n"
"Þar af leiðir ráðleggjum við að þú sendir inn nýja villuskýrslu með ‚apport-"
"bug‘ og búir til athugasemd í þessarri villu um þá skýrslu.\n"
"\n"
"Ertu alveg viss þú viljir halda áfram?"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:614
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:630
#: ../apport/ui.py:614 ../apport/ui.py:630
msgid "No additional information collected."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:681
#: ../apport/ui.py:681
msgid "What kind of problem do you want to report?"
msgstr "Hvers konar forrit viltu senda skýrslu um?"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:698
#: ../apport/ui.py:698
msgid "Unknown symptom"
msgstr "Óþekkt einkenni"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:699
#: ../apport/ui.py:699
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Einkennið „%s“ er ekki þekkt."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:730
#: ../apport/ui.py:730
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Eftir lokun þessa skilaboða, smelltu á forritsglugga til að skrá villu um "
"hann."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:740
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:745
#: ../apport/ui.py:740 ../apport/ui.py:745
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:759
#: ../apport/ui.py:759
msgid "%prog <report number>"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:761
#: ../apport/ui.py:761
msgid "Specify package name."
msgstr "Tilgreindu pakkaheiti."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:763
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:815
#: ../apport/ui.py:763 ../apport/ui.py:815
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:794
#: ../apport/ui.py:794
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:797
#: ../apport/ui.py:797
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:799
#: ../apport/ui.py:799
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:801
#: ../apport/ui.py:801
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:803
#: ../apport/ui.py:803
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:805
#: ../apport/ui.py:805
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:807
#: ../apport/ui.py:807
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:809
#: ../apport/ui.py:809
msgid "The provided pid is a hanging application."
msgstr "Gefna PID-ið er forrit sem hangir."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:811
#: ../apport/ui.py:811
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:813
#: ../apport/ui.py:813
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:817
#: ../apport/ui.py:817
msgid "Print the Apport version number."
msgstr "Gefa Apport útgáfunúmerið."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:968
#: ../apport/ui.py:968
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:969
#: ../apport/ui.py:969
msgid "Run gdb session"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:970
#: ../apport/ui.py:970
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:972
#: ../apport/ui.py:972
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1008
#: ../apport/ui.py:1008
msgid "Can't remember send report status settings"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1009
#: ../apport/ui.py:1009
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1068
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1078
#: ../apport/ui.py:1068 ../apport/ui.py:1078
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "Þessi vandamálaskýrsla á við forrit sem er ekki uppsett lengur."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1093
#: ../apport/ui.py:1093
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Vandamálið kom fyrir í forritunu %s sem er breytt síðan síðasta hrun varð."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1140
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1221
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1436
#: ../apport/ui.py:1140 ../apport/ui.py:1221 ../apport/ui.py:1436
msgid "This problem report is damaged and cannot be processed."
msgstr "Skýrslan er löskuð og ég get ekki unnið úr henni"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1130
#: ../apport/ui.py:1130
#, python-format
msgid ""
"This report is about a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1133
#: ../apport/ui.py:1133
#, python-format
msgid ""
"This report is about a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1145
#: ../apport/ui.py:1145
msgid "This report is about a package that is not installed."
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1149
#: ../apport/ui.py:1149
msgid "An error occurred while attempting to process this problem report:"
msgstr "Villa kom upp þegar reynt var að vinna þessa villuskýrslu:"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1148
#: ../apport/ui.py:1148
#, python-format
msgid ""
"You are about to report a bug against the deb package, but you also a have "
"snap published by %s installed. You can contact them via %s for help. Do you "
"want to continue with the bug report against the deb?"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1150
#: ../apport/ui.py:1150
#, python-format
msgid ""
"You are about to report a bug against the deb package, but you also a have "
"snap published by %s installed. For the snap, no contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help. Do you "
"want to continue with the bug report against the deb?"
msgstr ""

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1265
#: ../apport/ui.py:1265
msgid "Could not determine the package or source package name."
msgstr "Gat ekki ákveðið nafn pakka eða grunnpakka"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1283
#: ../apport/ui.py:1283
msgid "Unable to start web browser"
msgstr "Gat ekki ræst vefvafra"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1284
#: ../apport/ui.py:1284
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Gat ekki ræst vefvafra til að opna %s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1384
#: ../apport/ui.py:1384
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "Sláðu inn aðgangsupplýsingar þínar fyrir %s villukerfið."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1396
#: ../apport/ui.py:1396
msgid "Network problem"
msgstr "Vandamál með nettengingu"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1398
#: ../apport/ui.py:1398
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr "Get ekki tengst við gagnagrunn, athugaðu nettenginguna."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1425
#: ../apport/ui.py:1425
msgid "Memory exhaustion"
msgstr "Minnisvandamál"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1426
#: ../apport/ui.py:1426
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Kerfið þitt hefur ekki nóg vinnsluminni til að vinna úr þessari skýrslu."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1461
#: ../apport/ui.py:1461
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Ekki hægt að tilkynna vandamálið:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1517
#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1524
#: ../apport/ui.py:1517 ../apport/ui.py:1524
msgid "Problem already known"
msgstr "Vandamál þegar þekkt"

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1518
#: ../apport/ui.py:1518
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Þetta vandamál var þegar tilkynnt í villuskýrslunni sem birtist í "
"vefvafranum. Athugaðu hvort þú getur bætt við einhverjum gagnlegum "
"upplýsingum."

#: ../debian/tmp/usr/lib/python3.8/dist-packages/apport/ui.py:1525
#: ../apport/ui.py:1525
msgid "This problem was already reported to developers. Thank you!"
msgstr ""
"Þetta vandamál hefur nú þegar verið tilkynnt til þróunarteymis. Takk fyrir!"

#: ../debian/tmp/usr/share/apport/apport-kde.py:469
#: ../debian/tmp/usr/share/apport/apport-kde.py:504
#: ../debian/tmp/usr/share/apport/apport-kde.py:524
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:469 ../kde/apport-kde.py:504 ../kde/apport-kde.py:524
msgid "Apport"
msgstr "Apport"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4 ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Hrunskýrsla"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Því miður, upp kom innri villa.</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9 ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Hunsa frekari vandamál í þessarri útgáfu forrits"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10 ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "Skoða _hér"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Safna upplýsingum um vandamál</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16 ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Er að safna upplýsingum sem gætu hjálpað forriturum að laga vandann sem þú "
"tilkynnir"

#: ../debian/tmp/usr/share/apport/apport-kde.py:435
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
#: ../debian/tmp/usr/bin/apport-cli.py:267 ../gtk/apport-gtk.ui.h:17
#: ../bin/apport-cli.py:267 ../kde/apport-kde.py:435
msgid "Uploading problem information"
msgstr "Sendi vandamálsskýrslu"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18 ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Sendi vandamálsskýrslu</b></big>"

#: ../debian/tmp/usr/share/apport/apport-kde.py:436
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19 ../gtk/apport-gtk.ui.h:19
#: ../kde/apport-kde.py:436
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Er að senda upplýsingarnar á villukerfið. Þetta gæti tekið nokkrar mínútur."

#: ../debian/tmp/usr/share/apport/kernel_oops.py:29 ../data/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"Kerfið þitt verður kannski óstöðugt núna og þarf hugsanlega að endurræsa það."

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Notkun: %s <report> <target directory>"

#: ../bin/apport-unpack.py:42 ../debian/tmp/usr/bin/apport-unpack.py:42
msgid "Destination directory exists and is not empty."
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Safna kerfisupplýsingum"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Auðkenningar er krafist fyrir söfnun á kerfisupplýsingum fyrir þessa "
"villuskýrslu"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Vandamálaskýrslur kerfis"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr "Sláðu inn lykilorð til að fá aðgang að villuskýrslum kerfisforrita"

#: ../debian/tmp/usr/bin/apport-cli.py:80 ../bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr "Ýttu á einhvern lykil til að halda áfram..."

#: ../debian/tmp/usr/bin/apport-cli.py:87 ../bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr "Hvað viltu gera? Þú getur:"

#: ../debian/tmp/usr/bin/apport-cli.py:100 ../bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr "Veldu (%s);"

#: ../debian/tmp/usr/bin/apport-cli.py:164 ../bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr "(%i bæti)"

#: ../debian/tmp/usr/bin/apport-cli.py:195 ../bin/apport-cli.py:195
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Eftir að vandamálaskýrslan hefur verið send opnast sjálfkrafa netvafri með "
"formi.\n"
"Vinsamlegast fylltu það út."

#: ../debian/tmp/usr/bin/apport-cli.py:198 ../bin/apport-cli.py:198
#, python-format
msgid "&Send report (%s)"
msgstr "&Senda skýrslu (%s)"

#: ../debian/tmp/usr/bin/apport-cli.py:202 ../bin/apport-cli.py:202
msgid "&Examine locally"
msgstr "Skoða &hér"

#: ../debian/tmp/usr/bin/apport-cli.py:206 ../bin/apport-cli.py:206
msgid "&View report"
msgstr "&Lesa skýrslu"

#: ../debian/tmp/usr/bin/apport-cli.py:207 ../bin/apport-cli.py:207
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr "&Geyma skýrslu til að senda inn seinna eða til að færa á annan stað"

#: ../debian/tmp/usr/bin/apport-cli.py:208 ../bin/apport-cli.py:208
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Hætta við og h&unsa frekari hrun í þessari útgáfu forritsins"

#: ../debian/tmp/usr/bin/apport-cli.py:210
#: ../debian/tmp/usr/bin/apport-cli.py:287
#: ../debian/tmp/usr/bin/apport-cli.py:319
#: ../debian/tmp/usr/bin/apport-cli.py:340 ../bin/apport-cli.py:210
#: ../bin/apport-cli.py:287 ../bin/apport-cli.py:319 ../bin/apport-cli.py:340
msgid "&Cancel"
msgstr "&Hætta við"

#: ../debian/tmp/usr/bin/apport-cli.py:238 ../bin/apport-cli.py:238
msgid "Problem report file:"
msgstr "Skrá með upplýsingar um vandamál:"

#: ../debian/tmp/usr/bin/apport-cli.py:244
#: ../debian/tmp/usr/bin/apport-cli.py:249 ../bin/apport-cli.py:244
#: ../bin/apport-cli.py:249
msgid "&Confirm"
msgstr "&Staðfesta"

#: ../debian/tmp/usr/bin/apport-cli.py:248 ../bin/apport-cli.py:248
#, python-format
msgid "Error: %s"
msgstr "Villa: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:407
#: ../debian/tmp/usr/bin/apport-cli.py:254 ../bin/apport-cli.py:254
#: ../kde/apport-kde.py:407
msgid "Collecting problem information"
msgstr "Safna saman upplýsingum um vandamál"

#: ../debian/tmp/usr/bin/apport-cli.py:255 ../bin/apport-cli.py:255
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Þú getur sent inn skýrslu með þessum upplýsingum til að bæta forritið.\n"
"Þetta getur tekið nokkra stund."

#: ../debian/tmp/usr/bin/apport-cli.py:268 ../bin/apport-cli.py:268
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Verið er að senda upplýsingar sem safnað hefur verið í villukerfi.\n"
"Það getur tekið nokkrar mínútur."

#: ../debian/tmp/usr/bin/apport-cli.py:318 ../bin/apport-cli.py:318
msgid "&Done"
msgstr "&Lokið"

#: ../debian/tmp/usr/bin/apport-cli.py:324 ../bin/apport-cli.py:324
msgid "none"
msgstr "ekkert"

#: ../debian/tmp/usr/bin/apport-cli.py:325 ../bin/apport-cli.py:325
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Valið: %s. Margir valkostir:"

#: ../debian/tmp/usr/bin/apport-cli.py:341 ../bin/apport-cli.py:341
msgid "Choices:"
msgstr "Valkostir:"

#: ../debian/tmp/usr/bin/apport-cli.py:355 ../bin/apport-cli.py:355
msgid "Path to file (Enter to cancel):"
msgstr "Slóð skráar (Enter til að hætta við):"

#: ../debian/tmp/usr/bin/apport-cli.py:361 ../bin/apport-cli.py:361
msgid "File does not exist."
msgstr "Skrá er ekki til."

#: ../debian/tmp/usr/bin/apport-cli.py:363 ../bin/apport-cli.py:363
msgid "This is a directory."
msgstr "Þetta er mappa."

#: ../debian/tmp/usr/bin/apport-cli.py:369 ../bin/apport-cli.py:369
msgid "To continue, you must visit the following URL:"
msgstr "Þú verður að heimsækja eftirfarandi slóð til að halda áfram:"

#: ../debian/tmp/usr/bin/apport-cli.py:371 ../bin/apport-cli.py:371
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Þú getur ræst vafra núna eða afritað þessa slóð í vafra á annari tölvu."

#: ../debian/tmp/usr/bin/apport-cli.py:373 ../bin/apport-cli.py:373
msgid "Launch a browser now"
msgstr "Ræsa netvafra"

#: ../debian/tmp/usr/bin/apport-cli.py:388 ../bin/apport-cli.py:388
msgid "No pending crash reports. Try --help for more information."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Endurvakningin hékk í blá endann en lítur út fyrir að hafa klárast eðlilega."

#: ../debian/tmp/usr/share/apport/apport-kde.py:234 ../kde/apport-kde.py:234
msgid "Leave Closed"
msgstr "Skilja eftir lokað"

#: ../debian/tmp/usr/share/apport/apport-kde.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:381 ../kde/apport-kde.py:235
#: ../kde/apport-kde.py:381
msgid "Relaunch"
msgstr "Keyra aftur upp"

#: ../debian/tmp/usr/share/apport/apport-kde.py:315 ../kde/apport-kde.py:315
msgid "Username:"
msgstr "Notandanafn:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:316 ../kde/apport-kde.py:316
msgid "Password:"
msgstr "Lykilorð:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:406 ../kde/apport-kde.py:406
msgid "Collecting Problem Information"
msgstr "Safna saman upplýsingum um vandamál"

#: ../debian/tmp/usr/share/apport/apport-kde.py:408 ../kde/apport-kde.py:408
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Söfnuðum upplýsingum er hægt að koma til forritaranna til að bæta forritið. "
"Þetta gæti tekið nokkrar mínútur."

#: ../debian/tmp/usr/share/apport/apport-kde.py:434 ../kde/apport-kde.py:434
msgid "Uploading Problem Information"
msgstr "Sendi upplýsingar um vandamálið"

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Full skýrsla (mælt með; %s)"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Senda vandamálsskýrslu til forritaranna?</b></big>\n"
#~ "\n"
#~ "Eftir að skýrslan hefur verið send, vinsamlegast fylltu út formið í vafranum "
#~ "sem opnast sjálfkrafa."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "Ef þú varst ekki að gera eitthvað leynilegt (slá inn lykilorð eða aðrar "
#~ "persónulegar upplýsingar) geturðu hjálpað við að bæta forritið með því að "
#~ "tilkynna vandamálið."

#~ msgid "Application problem"
#~ msgstr "Forritsvandamál"

#~ msgid "_Send Report"
#~ msgstr "_Senda skýrslu"

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Ef þú varst ekki að gera eitthvað persónugreinanlegt (slá inn lykilorð eða \n"
#~ "aðrar persónulegar upplýsingar) getur þú hjálpað við að laga forritið með\n"
#~ "því að tilkynna vandamálið."

#~ msgid "Restart _Program"
#~ msgstr "_Endurræsa Forrit"

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">Því miður tókst ekki að setja upp eða "
#~ "uppfæra pakkann \"%s\"</span>"

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Minnkuð skýrsla (hæg nettenging; %s)"

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Hunsa frekari hrun þessarar forritsútgáfu"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "Þetta tekur nokkra stóra hluta úr skýrslunni. Þeir eru gagnlegir forriturum "
#~ "til að greina vandamálkið, en gætu verið of stórir til að að senda yfir hæga "
#~ "nettengingu."

#~ msgid "&Report Problem..."
#~ msgstr "&Tilkynna vandamál"

#~ msgid "The report belongs to a package that is not installed."
#~ msgstr "Þessi skýrsla tilheyrir pakka sem ekki er uppsettur"

#~ msgid "_Report Problem..."
#~ msgstr "_Tilkynna vandamál..."

#~ msgid "Kernel problem"
#~ msgstr "Kjarnavandi"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr ""
#~ "Þú getur hjálpað forriturunum að laga pakkann með því að senda inn "
#~ "tilkynningu."

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "Þetta er ekki alvöru %s pakki"

#~ msgid "Content of the report"
#~ msgstr "Innihald skýrslunnar"

#~ msgid "Package problem"
#~ msgstr "Pakkavandamál"

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "Það tókst hvorki að setja upp “%s“ eða uppfæra."

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s lokaði óviðbúið þann %s klukkan %s."

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "Kerfið þitt lenti í alvarlegum vanda með stýrikerfiskjarnann"

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "Þú getur hjálpað til með því að tilkynna vandann."

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Senda alla skýrsluna (mælt með þessu; %s)"

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Senda &stytta skýrslu (hæg nettenging; %s)"

#~ msgid "%prog [options] <apport problem report | crash ID>"
#~ msgstr "%prog [options] <apport problem report | crash ID>"

#~ msgid "Send an error report to help fix this problem"
#~ msgstr "Senda villuskýrslu til að hjálpa til við lausn þessa vandamáls"

#~ msgid "Force Closed"
#~ msgstr "Þvinga til að loka"

#~ msgid ""
#~ "This occured during a previous suspend and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Þetta gerðist áður meðan verið var í svæfingu og kom í veg fyrir "
#~ "endurvakningu úr því ástandi."

#~ msgid ""
#~ "This occured during a previous hibernate and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Þetta gerðist áður meðan verið var í dvala og kom í veg fyrir endurvakningu "
#~ "úr því ástandi."
