# Uzbek translation for apport
# Copyright (c) 2012 Rosetta Contributors and Canonical Ltd 2012
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2012.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-09-10 11:16+0200\n"
"PO-Revision-Date: 2012-12-20 18:03+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Uzbek <uz@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2018-05-08 05:20+0000\n"
"X-Generator: Launchpad (build 18623)\n"
"Language: uz\n"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1 ../gtk/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-kde.py:468
#: ../debian/tmp/usr/share/apport/apport-kde.py:503
#: ../debian/tmp/usr/share/apport/apport-kde.py:522 ../kde/apport-kde.py:468
#: ../kde/apport-kde.py:503 ../kde/apport-kde.py:522
msgid "Apport"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4 ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
#: ../debian/tmp/usr/share/apport/apport-gtk.py:303 ../gtk/apport-gtk.py:303
#: ../gtk/apport-gtk.ui.h:6 ../debian/tmp/usr/share/apport/apport-kde.py:240
#: ../kde/apport-kde.py:240
msgid "If you notice further problems, try restarting the computer."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7 ../gtk/apport-gtk.ui.h:7
msgid "Send an error report to help fix this problem"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "Ignore future problems of this program version"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
#: ../debian/tmp/usr/share/apport/apport-gtk.py:207
#: ../debian/tmp/usr/share/apport/apport-gtk.py:576 ../gtk/apport-gtk.py:207
#: ../gtk/apport-gtk.py:576 ../gtk/apport-gtk.ui.h:9
#: ../debian/tmp/usr/share/apport/apport-kde.py:291 ../kde/apport-kde.py:291
msgid "Show Details"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10 ../gtk/apport-gtk.ui.h:10
msgid "_Examine locally"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-gtk.py:290 ../gtk/apport-gtk.py:290
#: ../gtk/apport-gtk.ui.h:11 ../debian/tmp/usr/share/apport/apport-kde.py:233
#: ../kde/apport-kde.py:233
msgid "Leave Closed"
msgstr "Ёпилган қолдирилсин"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
#: ../debian/tmp/usr/share/apport/apport-gtk.py:219
#: ../debian/tmp/usr/share/apport/apport-gtk.py:287
#: ../debian/tmp/usr/share/apport/apport-gtk.py:306 ../gtk/apport-gtk.py:219
#: ../gtk/apport-gtk.py:287 ../gtk/apport-gtk.py:306 ../gtk/apport-gtk.ui.h:12
#: ../debian/tmp/usr/share/apport/apport-kde.py:230
#: ../debian/tmp/usr/share/apport/apport-kde.py:243 ../kde/apport-kde.py:230
#: ../kde/apport-kde.py:243
msgid "Continue"
msgstr "Давом этилсин"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../gtk/apport-gtk.ui.h:13
msgid "<big><b>Collecting problem information</b></big>"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14 ../gtk/apport-gtk.ui.h:14
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
#: ../debian/tmp/usr/bin/apport-cli.py:267 ../gtk/apport-gtk.ui.h:15
#: ../bin/apport-cli.py:267 ../debian/tmp/usr/share/apport/apport-kde.py:434
#: ../kde/apport-kde.py:434
msgid "Uploading problem information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16 ../gtk/apport-gtk.ui.h:16
msgid "<big><b>Uploading problem information</b></big>"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17 ../gtk/apport-gtk.ui.h:17
#: ../debian/tmp/usr/share/apport/apport-kde.py:435 ../kde/apport-kde.py:435
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:145
#: ../debian/tmp/usr/bin/apport-cli.py:166 ../gtk/apport-gtk.py:145
#: ../bin/apport-cli.py:166 ../debian/tmp/usr/share/apport/apport-kde.py:362
#: ../kde/apport-kde.py:362
msgid "(binary data)"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:160 ../gtk/apport-gtk.py:160
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:163 ../gtk/apport-gtk.py:163
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:168 ../gtk/apport-gtk.py:168
#: ../debian/tmp/usr/share/apport/apport-kde.py:199
#: ../debian/tmp/usr/share/apport/apport-kde.py:237 ../kde/apport-kde.py:199
#: ../kde/apport-kde.py:237
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "%s'да ички хато рўй берди."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:180
#: ../debian/tmp/usr/bin/apport-cli.py:194 ../gtk/apport-gtk.py:180
#: ../bin/apport-cli.py:194 ../debian/tmp/usr/share/apport/apport-kde.py:185
#: ../kde/apport-kde.py:185
msgid "Send problem report to the developers?"
msgstr "Тузувчиларга муаммо ҳақида хабар юборилсинми?"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:189 ../gtk/apport-gtk.py:189
#: ../debian/tmp/usr/share/apport/apport-kde.py:193 ../kde/apport-kde.py:193
msgid "Send"
msgstr "Юбориш"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:231 ../gtk/apport-gtk.py:231
msgid "Force Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:232
#: ../debian/tmp/usr/share/apport/apport-gtk.py:291 ../gtk/apport-gtk.py:232
#: ../gtk/apport-gtk.py:291 ../debian/tmp/usr/share/apport/apport-kde.py:234
#: ../debian/tmp/usr/share/apport/apport-kde.py:380 ../kde/apport-kde.py:234
#: ../kde/apport-kde.py:380
msgid "Relaunch"
msgstr "Қайта ишга туширилсин"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:241 ../gtk/apport-gtk.py:241
#, python-format
msgid "The application %s has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:245 ../gtk/apport-gtk.py:245
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:260 ../gtk/apport-gtk.py:260
#: ../debian/tmp/usr/share/apport/apport-kde.py:207 ../kde/apport-kde.py:207
#, python-format
msgid "Package: %s"
msgstr "Пакет: %s"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:267 ../gtk/apport-gtk.py:267
#: ../debian/tmp/usr/share/apport/apport-kde.py:213 ../kde/apport-kde.py:213
msgid "Sorry, a problem occurred while installing software."
msgstr "Дастур ўрнатилганда муаммо рўй берди."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:276
#: ../debian/tmp/usr/share/apport/apport-gtk.py:295 ../gtk/apport-gtk.py:276
#: ../gtk/apport-gtk.py:295 ../debian/tmp/usr/share/apport/apport-kde.py:219
#: ../kde/apport-kde.py:219
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "%s дастурида ички хато рўй берди."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:279 ../gtk/apport-gtk.py:279
#: ../debian/tmp/usr/share/apport/apport-kde.py:222 ../kde/apport-kde.py:222
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "%s дастури тўсатдан ёпилди."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:307 ../gtk/apport-gtk.py:307
#: ../debian/tmp/usr/share/apport/apport-kde.py:244 ../kde/apport-kde.py:244
msgid "Ignore future problems of this type"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.py:580 ../gtk/apport-gtk.py:580
#: ../debian/tmp/usr/share/apport/apport-kde.py:288 ../kde/apport-kde.py:288
msgid "Hide Details"
msgstr ""

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr ""

#: ../debian/tmp/usr/bin/apport-unpack.py:46 ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:314 ../kde/apport-kde.py:314
msgid "Username:"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:315 ../kde/apport-kde.py:315
msgid "Password:"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:405 ../kde/apport-kde.py:405
msgid "Collecting Problem Information"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:254 ../bin/apport-cli.py:254
#: ../debian/tmp/usr/share/apport/apport-kde.py:406 ../kde/apport-kde.py:406
msgid "Collecting problem information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:407 ../kde/apport-kde.py:407
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:433 ../kde/apport-kde.py:433
msgid "Uploading Problem Information"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../kde/apport-kde-mime.desktop.in.h:1
msgid "Report a problem..."
msgstr ""

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../kde/apport-kde-mime.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr ""

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr ""

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:66 ../debian/tmp/usr/bin/apport-retrace.py:63
#: ../debian/tmp/usr/bin/apport-valgrind.py:66 ../bin/apport-retrace.py:63
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr ""

#: ../debian/tmp/usr/share/apport/kernel_oops.py:29 ../data/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:34 ../bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:36 ../bin/apport-retrace.py:36
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:38 ../bin/apport-retrace.py:38
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:41 ../bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:43 ../bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:45 ../bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:47 ../bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:49 ../bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:51 ../bin/apport-retrace.py:51
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:53 ../bin/apport-retrace.py:53
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:55 ../bin/apport-retrace.py:55
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:59 ../bin/apport-retrace.py:59
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:61 ../bin/apport-retrace.py:61
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-retrace.py:65
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:67 ../bin/apport-retrace.py:67
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:69 ../bin/apport-retrace.py:69
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:78 ../bin/apport-retrace.py:78
msgid "You cannot use -C without -S. Stopping."
msgstr ""

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../debian/tmp/usr/bin/apport-retrace.py:111 ../bin/apport-retrace.py:111
msgid "OK to send these as attachments? [y/n]"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:125
#: ../apport/ui.py:125
msgid "This package does not seem to be installed correctly"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:130
#: ../apport/ui.py:130
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:147
#: ../apport/ui.py:147
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:276
#: ../apport/ui.py:276
msgid "unknown program"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:277
#: ../apport/ui.py:277
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:279
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1318
#: ../apport/ui.py:279 ../apport/ui.py:1318
#, python-format
msgid "Problem in %s"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:280
#: ../apport/ui.py:280
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:328
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:336
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:463
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:466
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:667
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1124
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1290
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1294
#: ../apport/ui.py:328 ../apport/ui.py:336 ../apport/ui.py:463
#: ../apport/ui.py:466 ../apport/ui.py:667 ../apport/ui.py:1124
#: ../apport/ui.py:1290 ../apport/ui.py:1294
msgid "Invalid problem report"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:329
#: ../apport/ui.py:329
msgid "You are not allowed to access this problem report."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:332
#: ../apport/ui.py:332
msgid "Error"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:333
#: ../apport/ui.py:333
msgid "There is not enough disk space available to process this report."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:417
#: ../apport/ui.py:417
msgid "No package specified"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:418
#: ../apport/ui.py:418
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:441
#: ../apport/ui.py:441
msgid "Permission denied"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:442
#: ../apport/ui.py:442
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:444
#: ../apport/ui.py:444
msgid "Invalid PID"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:445
#: ../apport/ui.py:445
msgid "The specified process ID does not belong to a program."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:464
#: ../apport/ui.py:464
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:467
#: ../apport/ui.py:467
#, python-format
msgid "Package %s does not exist"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:491
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:679
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:684
#: ../apport/ui.py:491 ../apport/ui.py:679 ../apport/ui.py:684
msgid "Cannot create report"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:506
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:569
#: ../apport/ui.py:506 ../apport/ui.py:552 ../apport/ui.py:569
msgid "Updating problem report"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:507
#: ../apport/ui.py:507
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:516
#: ../apport/ui.py:516
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:553
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:570
#: ../apport/ui.py:553 ../apport/ui.py:570
msgid "No additional information collected."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:621
#: ../apport/ui.py:621
msgid "What kind of problem do you want to report?"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:638
#: ../apport/ui.py:638
msgid "Unknown symptom"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:639
#: ../apport/ui.py:639
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:670
#: ../apport/ui.py:670
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:680
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:685
#: ../apport/ui.py:680 ../apport/ui.py:685
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:699
#: ../apport/ui.py:699
msgid "%prog <report number>"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:701
#: ../apport/ui.py:701
msgid "Specify package name."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:703
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:754
#: ../apport/ui.py:703 ../apport/ui.py:754
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:733
#: ../apport/ui.py:733
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:736
#: ../apport/ui.py:736
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:738
#: ../apport/ui.py:738
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:740
#: ../apport/ui.py:740
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:742
#: ../apport/ui.py:742
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:744
#: ../apport/ui.py:744
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:746
#: ../apport/ui.py:746
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:748
#: ../apport/ui.py:748
msgid "The provided pid is a hanging application."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:750
#: ../apport/ui.py:750
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:752
#: ../apport/ui.py:752
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:756
#: ../apport/ui.py:756
msgid "Print the Apport version number."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:895
#: ../apport/ui.py:895
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:896
#: ../apport/ui.py:896
msgid "Run gdb session"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:897
#: ../apport/ui.py:897
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:899
#: ../apport/ui.py:899
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:975
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:985
#: ../apport/ui.py:975 ../apport/ui.py:985
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1000
#: ../apport/ui.py:1000
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1047
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1081
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1296
#: ../apport/ui.py:1047 ../apport/ui.py:1081 ../apport/ui.py:1296
msgid "This problem report is damaged and cannot be processed."
msgstr ""

#. package does not exist
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1051
#: ../apport/ui.py:1051
msgid "The report belongs to a package that is not installed."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1055
#: ../apport/ui.py:1055
msgid "An error occurred while attempting to process this problem report:"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1125
#: ../apport/ui.py:1125
msgid "Could not determine the package or source package name."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1143
#: ../apport/ui.py:1143
msgid "Unable to start web browser"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1144
#: ../apport/ui.py:1144
#, python-format
msgid "Unable to start web browser to open %s."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1244
#: ../apport/ui.py:1244
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1256
#: ../apport/ui.py:1256
msgid "Network problem"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1258
#: ../apport/ui.py:1258
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1285
#: ../apport/ui.py:1285
msgid "Memory exhaustion"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1286
#: ../apport/ui.py:1286
msgid "Your system does not have enough memory to process this crash report."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1321
#: ../apport/ui.py:1321
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1377
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1384
#: ../apport/ui.py:1377 ../apport/ui.py:1384
msgid "Problem already known"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1378
#: ../apport/ui.py:1378
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1385
#: ../apport/ui.py:1385
msgid "This problem was already reported to developers. Thank you!"
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:80 ../bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:87 ../bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:100 ../bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:164 ../bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:195 ../bin/apport-cli.py:195
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:198 ../bin/apport-cli.py:198
#, python-format
msgid "&Send report (%s)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:202 ../bin/apport-cli.py:202
msgid "&Examine locally"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:206 ../bin/apport-cli.py:206
msgid "&View report"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:207 ../bin/apport-cli.py:207
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:208 ../bin/apport-cli.py:208
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:210
#: ../debian/tmp/usr/bin/apport-cli.py:287
#: ../debian/tmp/usr/bin/apport-cli.py:319
#: ../debian/tmp/usr/bin/apport-cli.py:340 ../bin/apport-cli.py:210
#: ../bin/apport-cli.py:287 ../bin/apport-cli.py:319 ../bin/apport-cli.py:340
msgid "&Cancel"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:238 ../bin/apport-cli.py:238
msgid "Problem report file:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:244
#: ../debian/tmp/usr/bin/apport-cli.py:249 ../bin/apport-cli.py:244
#: ../bin/apport-cli.py:249
msgid "&Confirm"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:248 ../bin/apport-cli.py:248
#, python-format
msgid "Error: %s"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:255 ../bin/apport-cli.py:255
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:268 ../bin/apport-cli.py:268
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:318 ../bin/apport-cli.py:318
msgid "&Done"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:324 ../bin/apport-cli.py:324
msgid "none"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:325 ../bin/apport-cli.py:325
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:341 ../bin/apport-cli.py:341
msgid "Choices:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:355 ../bin/apport-cli.py:355
msgid "Path to file (Enter to cancel):"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:361 ../bin/apport-cli.py:361
msgid "File does not exist."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:363 ../bin/apport-cli.py:363
msgid "This is a directory."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:369 ../bin/apport-cli.py:369
msgid "To continue, you must visit the following URL:"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:371 ../bin/apport-cli.py:371
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:373 ../bin/apport-cli.py:373
msgid "Launch a browser now"
msgstr ""

#: ../debian/tmp/usr/bin/apport-cli.py:387 ../bin/apport-cli.py:387
msgid "No pending crash reports. Try --help for more information."
msgstr ""
